#include "Lcore.h"

int main(const int argc, const char * argv[]){

  if (argc < 2) return 1;

  const int opt = atoi(argv[1]);
  gStyle->SetPalette(55);

  if (opt == 1){//wave function Ur
    MODEL::SetUr();
    double x[100], y[100];
    for (int i = 0; i < 100; i++){
      x[i] = 0.05 * i;
      y[i] = MODEL::Ur(x[i] / Phys::hbar);
    }
    TGraph * g0 = new TGraph(100, x, y);
    g0->SetLineColor(4);
    g0->SetLineWidth(2);
    g0->SetTitle("");
    g0->GetXaxis()->SetTitle("r (fm)");
    g0->GetXaxis()->CenterTitle(true);
    g0->GetXaxis()->SetTitleSize(0.06);
    g0->GetXaxis()->SetTitleOffset(1.15);
    g0->GetXaxis()->SetLabelSize(0.06);
    g0->GetXaxis()->SetRangeUser(0.0, 5.0);
    g0->GetXaxis()->SetNdivisions(6, 5, 0);
    g0->GetYaxis()->SetTitle("u(r) (GeV^{1/2})");
    g0->GetYaxis()->CenterTitle(true);
    g0->GetYaxis()->SetTitleSize(0.06);
    g0->GetYaxis()->SetTitleOffset(1.15);
    g0->GetYaxis()->SetLabelSize(0.06);
    g0->GetYaxis()->SetRangeUser(0.0, 0.5);
    g0->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetBottomMargin(0.15);
    c0->SetLeftMargin(0.15);
    g0->DrawClone("al");
    c0->Print("gallary/wf.pdf");
  }

  
  if (opt == 2){//Veff
    MODEL::SetVeff();
    double x[100], y[100];
    for (int i = 0; i < 100; i++){
      x[i] = 0.05 * i;
      y[i] = MODEL::Veff(x[i] / Phys::hbar);
    }
    TGraph * g0 = new TGraph(100, x, y);
    g0->SetLineColor(4);
    g0->SetLineWidth(2);
    g0->SetTitle("");
    g0->GetXaxis()->SetTitle("r (fm)");
    g0->GetXaxis()->CenterTitle(true);
    g0->GetXaxis()->SetTitleSize(0.06);
    g0->GetXaxis()->SetTitleOffset(1.15);
    g0->GetXaxis()->SetLabelSize(0.06);
    g0->GetXaxis()->SetRangeUser(0.0, 5.0);
    g0->GetXaxis()->SetNdivisions(6, 5, 0);
    g0->GetYaxis()->SetTitle("V_{eff} (GeV)");
    g0->GetYaxis()->CenterTitle(true);
    g0->GetYaxis()->SetTitleSize(0.06);
    g0->GetYaxis()->SetTitleOffset(1.15);
    g0->GetYaxis()->SetLabelSize(0.06);
    g0->GetYaxis()->SetRangeUser(-0.6, 0.2);
    g0->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetBottomMargin(0.15);
    c0->SetLeftMargin(0.15);
    g0->DrawClone("al");
    c0->Print("gallary/Veff.pdf"); 
  }


  if (opt == 3){//F(Q)
    MODEL::SetFQ();
    double x[100], y[100];
    for (int i = 0; i < 100; i++){
      x[i] = 0.02 * i;
      y[i] = MODEL::FQ(x[i]);
    }
    TGraph * g0 = new TGraph(100, x, y);
    g0->SetLineColor(4);
    g0->SetLineWidth(2);
    g0->SetTitle("");
    g0->GetXaxis()->SetTitle("Q (GeV)");
    g0->GetXaxis()->CenterTitle(true);
    g0->GetXaxis()->SetTitleSize(0.06);
    g0->GetXaxis()->SetTitleOffset(1.15);
    g0->GetXaxis()->SetLabelSize(0.06);
    g0->GetXaxis()->SetRangeUser(0.0, 2.0);
    g0->GetXaxis()->SetNdivisions(6, 5, 0);
    g0->GetYaxis()->SetTitle("F (GeV^{-1/2})");
    g0->GetYaxis()->CenterTitle(true);
    g0->GetYaxis()->SetTitleSize(0.06);
    g0->GetYaxis()->SetTitleOffset(1.15);
    g0->GetYaxis()->SetLabelSize(0.06);
    g0->GetYaxis()->SetRangeUser(0.0, 0.06);
    g0->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetBottomMargin(0.15);
    c0->SetLeftMargin(0.15);
    g0->DrawClone("al");
    c0->Print("gallary/FQ.pdf"); 
  }

  if (opt == 4){//invariant mass vertex
    TFile * fs = new TFile("result/raw.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h1 = (TH1D *) fs->Get("MpKK_BoundStateKK");
    TH1D * h2 = (TH1D *) fs->Get("MpKK_phi");
    TH1D * h3 = (TH1D *) fs->Get("MpKK_Lambda1520");
    TH1D * h4 = (TH1D *) fs->Get("MpKK_directKK");
    TH1D * h0a = (TH1D *) fs->Get("MpKp_BoundStateAll");
    TH1D * h1a = (TH1D *) fs->Get("MpKp_BoundStateKK");
    TH1D * h2a = (TH1D *) fs->Get("MpKp_phi");
    TH1D * h3a = (TH1D *) fs->Get("MpKp_Lambda1520");
    TH1D * h4a = (TH1D *) fs->Get("MpKp_directKK");
    TH1D * h0b = (TH1D *) fs->Get("MpKm_BoundStateAll");
    TH1D * h1b = (TH1D *) fs->Get("MpKm_BoundStateKK");
    TH1D * h2b = (TH1D *) fs->Get("MpKm_phi");
    TH1D * h3b = (TH1D *) fs->Get("MpKm_Lambda1520");
    TH1D * h4b = (TH1D *) fs->Get("MpKm_directKK");
    TH1D * h0c = (TH1D *) fs->Get("MKK_BoundStateAll");
    TH1D * h1c = (TH1D *) fs->Get("MKK_BoundStateKK");
    TH1D * h2c = (TH1D *) fs->Get("MKK_phi");
    TH1D * h3c = (TH1D *) fs->Get("MKK_Lambda1520");
    TH1D * h4c = (TH1D *) fs->Get("MKK_directKK");
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    double binsize = 0.2;//MeV
    h0->GetXaxis()->SetTitle("M(pKK) (GeV)");
    h0->GetXaxis()->CenterTitle(true);
    h0->GetXaxis()->SetTitleSize(0.06);
    h0->GetXaxis()->SetTitleOffset(1.15);
    h0->GetXaxis()->SetLabelSize(0.06);
    h0->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0->GetXaxis()->SetNdivisions(6, 5, 0);
    h0->GetYaxis()->SetTitle("counts / hour / MeV");
    h0->GetYaxis()->CenterTitle(true);
    h0->GetYaxis()->SetTitleSize(0.06);
    h0->GetYaxis()->SetTitleOffset(1.15);
    h0->GetYaxis()->SetLabelSize(0.06);
    h0->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0->GetYaxis()->SetNdivisions(5, 5, 0);
    h0a->GetXaxis()->SetTitle("M(pK^{+}) (GeV)");
    h0a->GetXaxis()->CenterTitle(true);
    h0a->GetXaxis()->SetTitleSize(0.06);
    h0a->GetXaxis()->SetTitleOffset(1.15);
    h0a->GetXaxis()->SetLabelSize(0.06);
    h0a->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0a->GetXaxis()->SetNdivisions(6, 5, 0);
    h0a->GetYaxis()->SetTitle("counts / hour / MeV");
    h0a->GetYaxis()->CenterTitle(true);
    h0a->GetYaxis()->SetTitleSize(0.06);
    h0a->GetYaxis()->SetTitleOffset(1.15);
    h0a->GetYaxis()->SetLabelSize(0.06);
    h0a->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0a->GetYaxis()->SetNdivisions(5, 5, 0);
    h0b->GetXaxis()->SetTitle("M(pK^{-}) (GeV)");
    h0b->GetXaxis()->CenterTitle(true);
    h0b->GetXaxis()->SetTitleSize(0.06);
    h0b->GetXaxis()->SetTitleOffset(1.15);
    h0b->GetXaxis()->SetLabelSize(0.06);
    h0b->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0b->GetXaxis()->SetNdivisions(6, 5, 0);
    h0b->GetYaxis()->SetTitle("counts / hour / MeV");
    h0b->GetYaxis()->CenterTitle(true);
    h0b->GetYaxis()->SetTitleSize(0.06);
    h0b->GetYaxis()->SetTitleOffset(1.15);
    h0b->GetYaxis()->SetLabelSize(0.06);
    h0b->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0b->GetYaxis()->SetNdivisions(5, 5, 0);
    h0c->GetXaxis()->SetTitle("M(K^{+}K^{-}) (GeV)");
    h0c->GetXaxis()->CenterTitle(true);
    h0c->GetXaxis()->SetTitleSize(0.06);
    h0c->GetXaxis()->SetTitleOffset(1.15);
    h0c->GetXaxis()->SetLabelSize(0.06);
    h0c->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0c->GetXaxis()->SetNdivisions(6, 5, 0);
    h0c->GetYaxis()->SetTitle("counts / hour / MeV");
    h0c->GetYaxis()->CenterTitle(true);
    h0c->GetYaxis()->SetTitleSize(0.06);
    h0c->GetYaxis()->SetTitleOffset(1.15);
    h0c->GetYaxis()->SetLabelSize(0.06);
    h0c->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    h0->Scale(lumi*time/binsize);
    h1->Scale(lumi*time/binsize);
    h2->Scale(lumi*time/binsize);
    h3->Scale(lumi*time/binsize);
    h4->Scale(lumi*time/binsize);
    h0a->Scale(lumi*time/binsize);
    h1a->Scale(lumi*time/binsize);
    h2a->Scale(lumi*time/binsize);
    h3a->Scale(lumi*time/binsize);
    h4a->Scale(lumi*time/binsize);
    h0b->Scale(lumi*time/binsize);
    h1b->Scale(lumi*time/binsize);
    h2b->Scale(lumi*time/binsize);
    h3b->Scale(lumi*time/binsize);
    h4b->Scale(lumi*time/binsize);
    h0c->Scale(lumi*time/binsize);
    h1c->Scale(lumi*time/binsize);
    h2c->Scale(lumi*time/binsize);
    h3c->Scale(lumi*time/binsize);
    h4c->Scale(lumi*time/binsize);
    //
    h0->SetStats(0);
    h0a->SetStats(0);
    h0b->SetStats(0);
    h0c->SetStats(0);
    //
    h0->SetLineColor(1);
    h1->SetLineColor(4);
    h2->SetLineColor(2);
    h3->SetLineColor(6);
    h4->SetLineColor(7);
    h0a->SetLineColor(1);
    h1a->SetLineColor(4);
    h2a->SetLineColor(2);
    h3a->SetLineColor(6);
    h4a->SetLineColor(7);
    h0b->SetLineColor(1);
    h1b->SetLineColor(4);
    h2b->SetLineColor(2);
    h3b->SetLineColor(6);
    h4b->SetLineColor(7);
    h0c->SetLineColor(1);
    h1c->SetLineColor(4);
    h2c->SetLineColor(2);
    h3c->SetLineColor(6);
    h4c->SetLineColor(7);
    //
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    h0->SetMaximum(15.0);
    h0->DrawClone("axis");
    h0->DrawClone("same");
    h1->DrawClone("same");
    h2->DrawClone("same");
    h3->DrawClone("same");
    h4->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Massraw.pdf(","pdf");//
    h0a->SetMaximum(25.0);
    h0a->DrawClone("axis");
    h0a->DrawClone("same");
    h1a->DrawClone("same");
    h2a->DrawClone("same");
    h3a->DrawClone("same");
    h4a->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Massraw.pdf","pdf");//
    h0b->SetMaximum(30.0);
    h0b->DrawClone("axis");
    h0b->DrawClone("same");
    h1b->DrawClone("same");
    h2b->DrawClone("same");
    h3b->Scale(1/20.);h3b->DrawClone("same");
    h4b->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production / 20", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Massraw.pdf","pdf");//
    h0c->SetMaximum(30.0);
    h0c->DrawClone("axis");
    h0c->DrawClone("same");
    h1c->DrawClone("same");
    h2c->Scale(1/50.);h2c->DrawClone("same");
    h3c->DrawClone("same");
    h4c->DrawClone("same");
    h0c->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production / 50", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Massraw.pdf)","pdf");
  }

  if (opt == 5){//Momentum vertex
    TFile * fs = new TFile("result/raw.root", "r");
    TH2D * d0a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateAll");
    TH2D * d1a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateKK");
    TH2D * d2a = (TH2D *) fs->Get("Momentum_p_Kp_phi");
    TH2D * d3a = (TH2D *) fs->Get("Momentum_p_Kp_Lambda1520");
    TH2D * d4a = (TH2D *) fs->Get("Momentum_p_Kp_KK");
    TH2D * d0b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateAll");
    TH2D * d1b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateKK");
    TH2D * d2b = (TH2D *) fs->Get("Momentum_p_Km_phi");
    TH2D * d3b = (TH2D *) fs->Get("Momentum_p_Km_Lambda1520");
    TH2D * d4b = (TH2D *) fs->Get("Momentum_p_Km_KK");
    TH2D * d0c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateAll");
    TH2D * d1c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateKK");
    TH2D * d2c = (TH2D *) fs->Get("Momentum_Kp_Km_phi");
    TH2D * d3c = (TH2D *) fs->Get("Momentum_Kp_Km_Lambda1520");
    TH2D * d4c = (TH2D *) fs->Get("Momentum_Kp_Km_KK");
    TGraph * g0a = new TGraph(1000);
    TGraph * g1a = new TGraph(1000);
    TGraph * g2a = new TGraph(1000);
    TGraph * g3a = new TGraph(1000);
    TGraph * g4a = new TGraph(1000);
    TGraph * g0b = new TGraph(1000);
    TGraph * g1b = new TGraph(1000);
    TGraph * g2b = new TGraph(1000);
    TGraph * g3b = new TGraph(1000);
    TGraph * g4b = new TGraph(1000);
    TGraph * g0c = new TGraph(1000);
    TGraph * g1c = new TGraph(1000);
    TGraph * g2c = new TGraph(1000);
    TGraph * g3c = new TGraph(1000);
    TGraph * g4c = new TGraph(1000);
    double x, y;
    for (int i = 0; i < 1000; i++){
      d0a->GetRandom2(x, y);
      g0a->SetPoint(i, x, y);
      d1a->GetRandom2(x, y);
      g1a->SetPoint(i, x, y);
      d2a->GetRandom2(x, y);
      g2a->SetPoint(i, x, y);
      d3a->GetRandom2(x, y);
      g3a->SetPoint(i, x, y);
      d4a->GetRandom2(x, y);
      g4a->SetPoint(i, x, y);
      d0b->GetRandom2(x, y);
      g0b->SetPoint(i, x, y);
      d1b->GetRandom2(x, y);
      g1b->SetPoint(i, x, y);
      d2b->GetRandom2(x, y);
      g2b->SetPoint(i, x, y);
      d3b->GetRandom2(x, y);
      g3b->SetPoint(i, x, y);
      d4b->GetRandom2(x, y);
      g4b->SetPoint(i, x, y);
      d0c->GetRandom2(x, y);
      g0c->SetPoint(i, x, y);
      d1c->GetRandom2(x, y);
      g1c->SetPoint(i, x, y);
      d2c->GetRandom2(x, y);
      g2c->SetPoint(i, x, y);
      d3c->GetRandom2(x, y);
      g3c->SetPoint(i, x, y);
      d4c->GetRandom2(x, y);
      g4c->SetPoint(i, x, y);
    }
    //
    d0a->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0a->GetXaxis()->CenterTitle(true);
    d0a->GetXaxis()->SetTitleSize(0.06);
    d0a->GetXaxis()->SetTitleOffset(1.15);
    d0a->GetXaxis()->SetLabelSize(0.06);
    d0a->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetXaxis()->SetNdivisions(6, 5, 0);
    d0a->GetYaxis()->SetTitle("P(p) (GeV)");
    d0a->GetYaxis()->CenterTitle(true);
    d0a->GetYaxis()->SetTitleSize(0.06);
    d0a->GetYaxis()->SetTitleOffset(1.15);
    d0a->GetYaxis()->SetLabelSize(0.06);
    d0a->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetYaxis()->SetNdivisions(5, 5, 0);
    d0b->GetXaxis()->SetTitle("P(K^{-}) (GeV)");
    d0b->GetXaxis()->CenterTitle(true);
    d0b->GetXaxis()->SetTitleSize(0.06);
    d0b->GetXaxis()->SetTitleOffset(1.15);
    d0b->GetXaxis()->SetLabelSize(0.06);
    d0b->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetXaxis()->SetNdivisions(6, 5, 0);
    d0b->GetYaxis()->SetTitle("P(p) (GeV)");
    d0b->GetYaxis()->CenterTitle(true);
    d0b->GetYaxis()->SetTitleSize(0.06);
    d0b->GetYaxis()->SetTitleOffset(1.15);
    d0b->GetYaxis()->SetLabelSize(0.06);
    d0b->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetYaxis()->SetNdivisions(5, 5, 0);
    d0c->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0c->GetXaxis()->CenterTitle(true);
    d0c->GetXaxis()->SetTitleSize(0.06);
    d0c->GetXaxis()->SetTitleOffset(1.15);
    d0c->GetXaxis()->SetLabelSize(0.06);
    d0c->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetXaxis()->SetNdivisions(6, 5, 0);
    d0c->GetYaxis()->SetTitle("P(K^{-}) (GeV)");
    d0c->GetYaxis()->CenterTitle(true);
    d0c->GetYaxis()->SetTitleSize(0.06);
    d0c->GetYaxis()->SetTitleOffset(1.15);
    d0c->GetYaxis()->SetLabelSize(0.06);
    d0c->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    d0a->SetStats(0);
    d0b->SetStats(0);
    d0c->SetStats(0);
    //
    g0a->SetMarkerStyle(20);
    g0a->SetMarkerColor(1);
    g0a->SetMarkerSize(0.6);
    g1a->SetMarkerStyle(21);
    g1a->SetMarkerColor(4);
    g1a->SetMarkerSize(0.6);
    g2a->SetMarkerStyle(22);
    g2a->SetMarkerColor(2);
    g2a->SetMarkerSize(0.6);
    g3a->SetMarkerStyle(23);
    g3a->SetMarkerColor(6);
    g3a->SetMarkerSize(0.6);
    g4a->SetMarkerStyle(25);
    g4a->SetMarkerColor(7);
    g4a->SetMarkerSize(0.6);
    g0b->SetMarkerStyle(20);
    g0b->SetMarkerColor(1);
    g0b->SetMarkerSize(0.6);
    g1b->SetMarkerStyle(21);
    g1b->SetMarkerColor(4);
    g1b->SetMarkerSize(0.6);
    g2b->SetMarkerStyle(22);
    g2b->SetMarkerColor(2);
    g2b->SetMarkerSize(0.6);
    g3b->SetMarkerStyle(23);
    g3b->SetMarkerColor(6);
    g3b->SetMarkerSize(0.6);
    g4b->SetMarkerStyle(25);
    g4b->SetMarkerColor(7);
    g4b->SetMarkerSize(0.6);
    g0c->SetMarkerStyle(20);
    g0c->SetMarkerColor(1);
    g0c->SetMarkerSize(0.6);
    g1c->SetMarkerStyle(21);
    g1c->SetMarkerColor(4);
    g1c->SetMarkerSize(0.6);
    g2c->SetMarkerStyle(22);
    g2c->SetMarkerColor(2);
    g2c->SetMarkerSize(0.6);
    g3c->SetMarkerStyle(23);
    g3c->SetMarkerColor(6);
    g3c->SetMarkerSize(0.6);
    g4c->SetMarkerStyle(25);
    g4c->SetMarkerColor(7);
    g4c->SetMarkerSize(0.6);
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(g0a, "pKK from N-#phi", "p");
    leg->AddEntry(g1a, "only KK from N-#phi", "p");
    leg->AddEntry(g2a, "#phi production", "p");
    leg->AddEntry(g3a, "#Lambda(1520) production", "p");
    leg->AddEntry(g4a, "direct KK production", "p");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    //
    d0a->DrawClone("axis");
    g0a->DrawClone("psame");
    g1a->DrawClone("psame");
    g2a->DrawClone("psame");
    g3a->DrawClone("psame");
    g4a->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumraw.pdf(","pdf");//
    d0a->SetTitle("pKK from N-#phi");
    d0a->DrawClone("axis");
    d0a->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0a->SetTitle("only KK from N-#phi");
    d0a->DrawClone("axis");
    d1a->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0a->SetTitle("#phi production");
    d0a->DrawClone("axis");
    d2a->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0a->SetTitle("#Lambda(1520) production");
    d0a->DrawClone("axis");
    d3a->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//    
    d0a->SetTitle("direct KK production");
    d0a->DrawClone("axis");
    d4a->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    //
    d0b->DrawClone("axis");
    g0b->DrawClone("psame");
    g1b->DrawClone("psame");
    g2b->DrawClone("psame");
    g3b->DrawClone("psame");
    g4b->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumraw.pdf(","pdf");//
    d0b->SetTitle("pKK from N-#phi");
    d0b->DrawClone("axis");
    d0b->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0b->SetTitle("only KK from N-#phi");
    d0b->DrawClone("axis");
    d1b->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0b->SetTitle("#phi production");
    d0b->DrawClone("axis");
    d2b->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0b->SetTitle("#Lambda(1520) production");
    d0b->DrawClone("axis");
    d3b->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//    
    d0b->SetTitle("direct KK production");
    d0b->DrawClone("axis");
    d4b->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    //
    d0c->DrawClone("axis");
    g0c->DrawClone("psame");
    g1c->DrawClone("psame");
    g2c->DrawClone("psame");
    g3c->DrawClone("psame");
    g4c->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumraw.pdf(","pdf");//
    d0c->SetTitle("pKK from N-#phi");
    d0c->DrawClone("axis");
    d0c->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0c->SetTitle("only KK from N-#phi");
    d0c->DrawClone("axis");
    d1c->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0c->SetTitle("#phi production");
    d0c->DrawClone("axis");
    d2c->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//
    d0c->SetTitle("#Lambda(1520) production");
    d0c->DrawClone("axis");
    d3c->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf","pdf");//    
    d0c->SetTitle("direct KK production");
    d0c->DrawClone("axis");
    d4c->DrawClone("colsame");
    c0->Print("gallary/Momentumraw.pdf)","pdf");//
  }

  if (opt == 6){//P-theta vertex
    TFile * fs = new TFile("result/raw.root", "r");
    TH2D * r0a = (TH2D *) fs->Get("PTheta_p_BoundStateAll");
    TH2D * r0b = (TH2D *) fs->Get("PTheta_Kp_BoundStateAll");
    TH2D * r0c = (TH2D *) fs->Get("PTheta_Km_BoundStateAll");
    TH2D * r1a = (TH2D *) fs->Get("PTheta_p_BoundStateKK");
    TH2D * r1b = (TH2D *) fs->Get("PTheta_Kp_BoundStateKK");
    TH2D * r1c = (TH2D *) fs->Get("PTheta_Km_BoundStateKK");
    TH2D * r2a = (TH2D *) fs->Get("PTheta_p_phi");
    TH2D * r2b = (TH2D *) fs->Get("PTheta_Kp_phi");
    TH2D * r2c = (TH2D *) fs->Get("PTheta_Km_phi");
    TH2D * r3a = (TH2D *) fs->Get("PTheta_p_Lambda1520");
    TH2D * r3b = (TH2D *) fs->Get("PTheta_Kp_Lambda1520");
    TH2D * r3c = (TH2D *) fs->Get("PTheta_Km_Lambda1520");
    TH2D * r4a = (TH2D *) fs->Get("PTheta_p_KK");
    TH2D * r4b = (TH2D *) fs->Get("PTheta_Kp_KK");
    TH2D * r4c = (TH2D *) fs->Get("PTheta_Km_KK");
    TH2D * rB = new TH2D("rB", "", 1, 0.0, 90.0, 1, 0.0, 2.0);
    rB->SetStats(0);
    rB->GetXaxis()->SetTitle("#theta (deg)");
    rB->GetXaxis()->CenterTitle(true);
    rB->GetXaxis()->SetTitleSize(0.06);
    rB->GetXaxis()->SetTitleOffset(1.15);
    rB->GetXaxis()->SetLabelSize(0.06);
    rB->GetXaxis()->SetRangeUser(0.0, 90.0);
    rB->GetXaxis()->SetNdivisions(6, 5, 0);
    rB->GetYaxis()->SetTitle("P (GeV)");
    rB->GetYaxis()->CenterTitle(true);
    rB->GetYaxis()->SetTitleSize(0.06);
    rB->GetYaxis()->SetTitleOffset(1.15);
    rB->GetYaxis()->SetLabelSize(0.06);
    rB->GetYaxis()->SetRangeUser(0.0, 2.0);
    rB->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    rB->SetTitle("proton from N-#phi");
    rB->DrawClone("axis");
    r0a->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf(", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r0b->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r0c->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");//
    rB->SetTitle("proton with N-#phi production");
    rB->DrawClone("axis");
    r1a->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r1b->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r1c->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");//
    rB->SetTitle("proton with #phi production");
    rB->DrawClone("axis");
    r2a->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{+} from #phi");
    rB->DrawClone("axis");
    r2b->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{-} from #phi");
    rB->DrawClone("axis");
    r2c->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");//
    rB->SetTitle("proton from #Lambda(1520)");
    rB->DrawClone("axis");
    r3a->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{+} with #Lambda(1520) production");
    rB->DrawClone("axis");
    r3b->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{-} from #Lambda(1520)");
    rB->DrawClone("axis");
    r3c->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");//
    rB->SetTitle("proton with direct KK production");
    rB->DrawClone("axis");
    r4a->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{+} from direct KK production");
    rB->DrawClone("axis");
    r4b->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf", "pdf");
    rB->SetTitle("K^{-} from direct KK production");
    rB->DrawClone("axis");
    r4c->Draw("colsame");
    c0->Print("gallary/PThetaraw.pdf)", "pdf");//
  }

  if (opt == 7){//invariant mass detected d
    TFile * fs = new TFile("result/detected.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h1 = (TH1D *) fs->Get("MpKK_BoundStateKK");
    TH1D * h2 = (TH1D *) fs->Get("MpKK_phi");
    TH1D * h3 = (TH1D *) fs->Get("MpKK_Lambda1520");
    TH1D * h4 = (TH1D *) fs->Get("MpKK_directKK");
    TH1D * h0a = (TH1D *) fs->Get("MpKp_BoundStateAll");
    TH1D * h1a = (TH1D *) fs->Get("MpKp_BoundStateKK");
    TH1D * h2a = (TH1D *) fs->Get("MpKp_phi");
    TH1D * h3a = (TH1D *) fs->Get("MpKp_Lambda1520");
    TH1D * h4a = (TH1D *) fs->Get("MpKp_directKK");
    TH1D * h0b = (TH1D *) fs->Get("MpKm_BoundStateAll");
    TH1D * h1b = (TH1D *) fs->Get("MpKm_BoundStateKK");
    TH1D * h2b = (TH1D *) fs->Get("MpKm_phi");
    TH1D * h3b = (TH1D *) fs->Get("MpKm_Lambda1520");
    TH1D * h4b = (TH1D *) fs->Get("MpKm_directKK");
    TH1D * h0c = (TH1D *) fs->Get("MKK_BoundStateAll");
    TH1D * h1c = (TH1D *) fs->Get("MKK_BoundStateKK");
    TH1D * h2c = (TH1D *) fs->Get("MKK_phi");
    TH1D * h3c = (TH1D *) fs->Get("MKK_Lambda1520");
    TH1D * h4c = (TH1D *) fs->Get("MKK_directKK");
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    double binsize = 0.2;//MeV
    h0->GetXaxis()->SetTitle("M(pKK) (GeV)");
    h0->GetXaxis()->CenterTitle(true);
    h0->GetXaxis()->SetTitleSize(0.06);
    h0->GetXaxis()->SetTitleOffset(1.15);
    h0->GetXaxis()->SetLabelSize(0.06);
    h0->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0->GetXaxis()->SetNdivisions(6, 5, 0);
    h0->GetYaxis()->SetTitle("counts / hour / MeV");
    h0->GetYaxis()->CenterTitle(true);
    h0->GetYaxis()->SetTitleSize(0.06);
    h0->GetYaxis()->SetTitleOffset(1.15);
    h0->GetYaxis()->SetLabelSize(0.06);
    h0->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0->GetYaxis()->SetNdivisions(5, 5, 0);
    h0a->GetXaxis()->SetTitle("M(pK^{+}) (GeV)");
    h0a->GetXaxis()->CenterTitle(true);
    h0a->GetXaxis()->SetTitleSize(0.06);
    h0a->GetXaxis()->SetTitleOffset(1.15);
    h0a->GetXaxis()->SetLabelSize(0.06);
    h0a->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0a->GetXaxis()->SetNdivisions(6, 5, 0);
    h0a->GetYaxis()->SetTitle("counts / hour / MeV");
    h0a->GetYaxis()->CenterTitle(true);
    h0a->GetYaxis()->SetTitleSize(0.06);
    h0a->GetYaxis()->SetTitleOffset(1.15);
    h0a->GetYaxis()->SetLabelSize(0.06);
    h0a->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0a->GetYaxis()->SetNdivisions(5, 5, 0);
    h0b->GetXaxis()->SetTitle("M(pK^{-}) (GeV)");
    h0b->GetXaxis()->CenterTitle(true);
    h0b->GetXaxis()->SetTitleSize(0.06);
    h0b->GetXaxis()->SetTitleOffset(1.15);
    h0b->GetXaxis()->SetLabelSize(0.06);
    h0b->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0b->GetXaxis()->SetNdivisions(6, 5, 0);
    h0b->GetYaxis()->SetTitle("counts / hour / MeV");
    h0b->GetYaxis()->CenterTitle(true);
    h0b->GetYaxis()->SetTitleSize(0.06);
    h0b->GetYaxis()->SetTitleOffset(1.15);
    h0b->GetYaxis()->SetLabelSize(0.06);
    h0b->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0b->GetYaxis()->SetNdivisions(5, 5, 0);
    h0c->GetXaxis()->SetTitle("M(K^{+}K^{-}) (GeV)");
    h0c->GetXaxis()->CenterTitle(true);
    h0c->GetXaxis()->SetTitleSize(0.06);
    h0c->GetXaxis()->SetTitleOffset(1.15);
    h0c->GetXaxis()->SetLabelSize(0.06);
    h0c->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0c->GetXaxis()->SetNdivisions(6, 5, 0);
    h0c->GetYaxis()->SetTitle("counts / hour / MeV");
    h0c->GetYaxis()->CenterTitle(true);
    h0c->GetYaxis()->SetTitleSize(0.06);
    h0c->GetYaxis()->SetTitleOffset(1.15);
    h0c->GetYaxis()->SetLabelSize(0.06);
    h0c->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    h0->Scale(lumi*time/binsize);
    h1->Scale(lumi*time/binsize);
    h2->Scale(lumi*time/binsize);
    h3->Scale(lumi*time/binsize);
    h4->Scale(lumi*time/binsize);
    h0a->Scale(lumi*time/binsize);
    h1a->Scale(lumi*time/binsize);
    h2a->Scale(lumi*time/binsize);
    h3a->Scale(lumi*time/binsize);
    h4a->Scale(lumi*time/binsize);
    h0b->Scale(lumi*time/binsize);
    h1b->Scale(lumi*time/binsize);
    h2b->Scale(lumi*time/binsize);
    h3b->Scale(lumi*time/binsize);
    h4b->Scale(lumi*time/binsize);
    h0c->Scale(lumi*time/binsize);
    h1c->Scale(lumi*time/binsize);
    h2c->Scale(lumi*time/binsize);
    h3c->Scale(lumi*time/binsize);
    h4c->Scale(lumi*time/binsize);
    //
    h0->SetStats(0);
    h0a->SetStats(0);
    h0b->SetStats(0);
    h0c->SetStats(0);
    //
    h0->SetLineColor(1);
    h1->SetLineColor(4);
    h2->SetLineColor(2);
    h3->SetLineColor(6);
    h4->SetLineColor(7);
    h0a->SetLineColor(1);
    h1a->SetLineColor(4);
    h2a->SetLineColor(2);
    h3a->SetLineColor(6);
    h4a->SetLineColor(7);
    h0b->SetLineColor(1);
    h1b->SetLineColor(4);
    h2b->SetLineColor(2);
    h3b->SetLineColor(6);
    h4b->SetLineColor(7);
    h0c->SetLineColor(1);
    h1c->SetLineColor(4);
    h2c->SetLineColor(2);
    h3c->SetLineColor(6);
    h4c->SetLineColor(7);
    //
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    h0->SetMaximum(0.15);
    h0->DrawClone("axis");
    h0->DrawClone("same");
    h1->DrawClone("same");
    h2->DrawClone("same");
    h3->DrawClone("same");
    h4->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Massdetected.pdf(","pdf");//
    h0a->SetMaximum(0.1);
    h0a->DrawClone("axis");
    h0a->DrawClone("same");
    h1a->DrawClone("same");
    h2a->DrawClone("same");
    h3a->DrawClone("same");
    h4a->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Massdetected.pdf","pdf");//
    h0b->SetMaximum(0.1);
    h0b->DrawClone("axis");
    h0b->DrawClone("same");
    h1b->DrawClone("same");
    h2b->DrawClone("same");
    h3b->Scale(1/20.);h3b->DrawClone("same");
    h4b->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production / 20", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Massdetected.pdf","pdf");//
    h0c->SetMaximum(0.1);
    h0c->DrawClone("axis");
    h0c->DrawClone("same");
    h1c->DrawClone("same");
    h2c->Scale(1/20.);h2c->DrawClone("same");
    h3c->DrawClone("same");
    h4c->DrawClone("same");
    h0c->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production / 20", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Massdetected.pdf)","pdf");
  }

  if (opt == 8){//Momentum detected
    TFile * fs = new TFile("result/detected.root", "r");
    TH2D * d0a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateAll");
    TH2D * d1a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateKK");
    TH2D * d2a = (TH2D *) fs->Get("Momentum_p_Kp_phi");
    TH2D * d3a = (TH2D *) fs->Get("Momentum_p_Kp_Lambda1520");
    TH2D * d4a = (TH2D *) fs->Get("Momentum_p_Kp_KK");
    TH2D * d0b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateAll");
    TH2D * d1b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateKK");
    TH2D * d2b = (TH2D *) fs->Get("Momentum_p_Km_phi");
    TH2D * d3b = (TH2D *) fs->Get("Momentum_p_Km_Lambda1520");
    TH2D * d4b = (TH2D *) fs->Get("Momentum_p_Km_KK");
    TH2D * d0c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateAll");
    TH2D * d1c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateKK");
    TH2D * d2c = (TH2D *) fs->Get("Momentum_Kp_Km_phi");
    TH2D * d3c = (TH2D *) fs->Get("Momentum_Kp_Km_Lambda1520");
    TH2D * d4c = (TH2D *) fs->Get("Momentum_Kp_Km_KK");
    TGraph * g0a = new TGraph(1000);
    TGraph * g1a = new TGraph(1000);
    TGraph * g2a = new TGraph(1000);
    TGraph * g3a = new TGraph(1000);
    TGraph * g4a = new TGraph(1000);
    TGraph * g0b = new TGraph(1000);
    TGraph * g1b = new TGraph(1000);
    TGraph * g2b = new TGraph(1000);
    TGraph * g3b = new TGraph(1000);
    TGraph * g4b = new TGraph(1000);
    TGraph * g0c = new TGraph(1000);
    TGraph * g1c = new TGraph(1000);
    TGraph * g2c = new TGraph(1000);
    TGraph * g3c = new TGraph(1000);
    TGraph * g4c = new TGraph(1000);
    double x, y;
    for (int i = 0; i < 1000; i++){
      d0a->GetRandom2(x, y);
      g0a->SetPoint(i, x, y);
      d1a->GetRandom2(x, y);
      g1a->SetPoint(i, x, y);
      d2a->GetRandom2(x, y);
      g2a->SetPoint(i, x, y);
      d3a->GetRandom2(x, y);
      g3a->SetPoint(i, x, y);
      d4a->GetRandom2(x, y);
      g4a->SetPoint(i, x, y);
      d0b->GetRandom2(x, y);
      g0b->SetPoint(i, x, y);
      d1b->GetRandom2(x, y);
      g1b->SetPoint(i, x, y);
      d2b->GetRandom2(x, y);
      g2b->SetPoint(i, x, y);
      d3b->GetRandom2(x, y);
      g3b->SetPoint(i, x, y);
      d4b->GetRandom2(x, y);
      g4b->SetPoint(i, x, y);
      d0c->GetRandom2(x, y);
      g0c->SetPoint(i, x, y);
      d1c->GetRandom2(x, y);
      g1c->SetPoint(i, x, y);
      d2c->GetRandom2(x, y);
      g2c->SetPoint(i, x, y);
      d3c->GetRandom2(x, y);
      g3c->SetPoint(i, x, y);
      d4c->GetRandom2(x, y);
      g4c->SetPoint(i, x, y);
    }
    //
    d0a->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0a->GetXaxis()->CenterTitle(true);
    d0a->GetXaxis()->SetTitleSize(0.06);
    d0a->GetXaxis()->SetTitleOffset(1.15);
    d0a->GetXaxis()->SetLabelSize(0.06);
    d0a->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetXaxis()->SetNdivisions(6, 5, 0);
    d0a->GetYaxis()->SetTitle("P(p) (GeV)");
    d0a->GetYaxis()->CenterTitle(true);
    d0a->GetYaxis()->SetTitleSize(0.06);
    d0a->GetYaxis()->SetTitleOffset(1.15);
    d0a->GetYaxis()->SetLabelSize(0.06);
    d0a->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetYaxis()->SetNdivisions(5, 5, 0);
    d0b->GetXaxis()->SetTitle("P(K^{-}) (GeV)");
    d0b->GetXaxis()->CenterTitle(true);
    d0b->GetXaxis()->SetTitleSize(0.06);
    d0b->GetXaxis()->SetTitleOffset(1.15);
    d0b->GetXaxis()->SetLabelSize(0.06);
    d0b->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetXaxis()->SetNdivisions(6, 5, 0);
    d0b->GetYaxis()->SetTitle("P(p) (GeV)");
    d0b->GetYaxis()->CenterTitle(true);
    d0b->GetYaxis()->SetTitleSize(0.06);
    d0b->GetYaxis()->SetTitleOffset(1.15);
    d0b->GetYaxis()->SetLabelSize(0.06);
    d0b->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetYaxis()->SetNdivisions(5, 5, 0);
    d0c->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0c->GetXaxis()->CenterTitle(true);
    d0c->GetXaxis()->SetTitleSize(0.06);
    d0c->GetXaxis()->SetTitleOffset(1.15);
    d0c->GetXaxis()->SetLabelSize(0.06);
    d0c->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetXaxis()->SetNdivisions(6, 5, 0);
    d0c->GetYaxis()->SetTitle("P(K^{-}) (GeV)");
    d0c->GetYaxis()->CenterTitle(true);
    d0c->GetYaxis()->SetTitleSize(0.06);
    d0c->GetYaxis()->SetTitleOffset(1.15);
    d0c->GetYaxis()->SetLabelSize(0.06);
    d0c->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    d0a->SetStats(0);
    d0b->SetStats(0);
    d0c->SetStats(0);
    //
    g0a->SetMarkerStyle(20);
    g0a->SetMarkerColor(1);
    g0a->SetMarkerSize(0.6);
    g1a->SetMarkerStyle(21);
    g1a->SetMarkerColor(4);
    g1a->SetMarkerSize(0.6);
    g2a->SetMarkerStyle(22);
    g2a->SetMarkerColor(2);
    g2a->SetMarkerSize(0.6);
    g3a->SetMarkerStyle(23);
    g3a->SetMarkerColor(6);
    g3a->SetMarkerSize(0.6);
    g4a->SetMarkerStyle(25);
    g4a->SetMarkerColor(7);
    g4a->SetMarkerSize(0.6);
    g0b->SetMarkerStyle(20);
    g0b->SetMarkerColor(1);
    g0b->SetMarkerSize(0.6);
    g1b->SetMarkerStyle(21);
    g1b->SetMarkerColor(4);
    g1b->SetMarkerSize(0.6);
    g2b->SetMarkerStyle(22);
    g2b->SetMarkerColor(2);
    g2b->SetMarkerSize(0.6);
    g3b->SetMarkerStyle(23);
    g3b->SetMarkerColor(6);
    g3b->SetMarkerSize(0.6);
    g4b->SetMarkerStyle(25);
    g4b->SetMarkerColor(7);
    g4b->SetMarkerSize(0.6);
    g0c->SetMarkerStyle(20);
    g0c->SetMarkerColor(1);
    g0c->SetMarkerSize(0.6);
    g1c->SetMarkerStyle(21);
    g1c->SetMarkerColor(4);
    g1c->SetMarkerSize(0.6);
    g2c->SetMarkerStyle(22);
    g2c->SetMarkerColor(2);
    g2c->SetMarkerSize(0.6);
    g3c->SetMarkerStyle(23);
    g3c->SetMarkerColor(6);
    g3c->SetMarkerSize(0.6);
    g4c->SetMarkerStyle(25);
    g4c->SetMarkerColor(7);
    g4c->SetMarkerSize(0.6);
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(g0a, "pKK from N-#phi", "p");
    leg->AddEntry(g1a, "only KK from N-#phi", "p");
    leg->AddEntry(g2a, "#phi production", "p");
    leg->AddEntry(g3a, "#Lambda(1520) production", "p");
    leg->AddEntry(g4a, "direct KK production", "p");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    //
    d0a->DrawClone("axis");
    g0a->DrawClone("psame");
    g1a->DrawClone("psame");
    g2a->DrawClone("psame");
    g3a->DrawClone("psame");
    g4a->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumdetected.pdf(","pdf");//
    d0a->SetTitle("pKK from N-#phi");
    d0a->DrawClone("axis");
    d0a->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0a->SetTitle("only KK from N-#phi");
    d0a->DrawClone("axis");
    d1a->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0a->SetTitle("#phi production");
    d0a->DrawClone("axis");
    d2a->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0a->SetTitle("#Lambda(1520) production");
    d0a->DrawClone("axis");
    d3a->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//    
    d0a->SetTitle("direct KK production");
    d0a->DrawClone("axis");
    d4a->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    //
    d0b->DrawClone("axis");
    g0b->DrawClone("psame");
    g1b->DrawClone("psame");
    g2b->DrawClone("psame");
    g3b->DrawClone("psame");
    g4b->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumdetected.pdf(","pdf");//
    d0b->SetTitle("pKK from N-#phi");
    d0b->DrawClone("axis");
    d0b->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0b->SetTitle("only KK from N-#phi");
    d0b->DrawClone("axis");
    d1b->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0b->SetTitle("#phi production");
    d0b->DrawClone("axis");
    d2b->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0b->SetTitle("#Lambda(1520) production");
    d0b->DrawClone("axis");
    d3b->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//    
    d0b->SetTitle("direct KK production");
    d0b->DrawClone("axis");
    d4b->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    //
    d0c->DrawClone("axis");
    g0c->DrawClone("psame");
    g1c->DrawClone("psame");
    g2c->DrawClone("psame");
    g3c->DrawClone("psame");
    g4c->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumdetected.pdf(","pdf");//
    d0c->SetTitle("pKK from N-#phi");
    d0c->DrawClone("axis");
    d0c->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0c->SetTitle("only KK from N-#phi");
    d0c->DrawClone("axis");
    d1c->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0c->SetTitle("#phi production");
    d0c->DrawClone("axis");
    d2c->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//
    d0c->SetTitle("#Lambda(1520) production");
    d0c->DrawClone("axis");
    d3c->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf","pdf");//    
    d0c->SetTitle("direct KK production");
    d0c->DrawClone("axis");
    d4c->DrawClone("colsame");
    c0->Print("gallary/Momentumdetected.pdf)","pdf");//
  }

  if (opt == 9){//P-theta detected
    TFile * fs = new TFile("result/detected.root", "r");
    TH2D * r0a = (TH2D *) fs->Get("PTheta_p_BoundStateAll");
    TH2D * r0b = (TH2D *) fs->Get("PTheta_Kp_BoundStateAll");
    TH2D * r0c = (TH2D *) fs->Get("PTheta_Km_BoundStateAll");
    TH2D * r1a = (TH2D *) fs->Get("PTheta_p_BoundStateKK");
    TH2D * r1b = (TH2D *) fs->Get("PTheta_Kp_BoundStateKK");
    TH2D * r1c = (TH2D *) fs->Get("PTheta_Km_BoundStateKK");
    TH2D * r2a = (TH2D *) fs->Get("PTheta_p_phi");
    TH2D * r2b = (TH2D *) fs->Get("PTheta_Kp_phi");
    TH2D * r2c = (TH2D *) fs->Get("PTheta_Km_phi");
    TH2D * r3a = (TH2D *) fs->Get("PTheta_p_Lambda1520");
    TH2D * r3b = (TH2D *) fs->Get("PTheta_Kp_Lambda1520");
    TH2D * r3c = (TH2D *) fs->Get("PTheta_Km_Lambda1520");
    TH2D * r4a = (TH2D *) fs->Get("PTheta_p_KK");
    TH2D * r4b = (TH2D *) fs->Get("PTheta_Kp_KK");
    TH2D * r4c = (TH2D *) fs->Get("PTheta_Km_KK");
    TH2D * rB = new TH2D("rB", "", 1, 0.0, 90.0, 1, 0.0, 2.0);
    rB->SetStats(0);
    rB->GetXaxis()->SetTitle("#theta (deg)");
    rB->GetXaxis()->CenterTitle(true);
    rB->GetXaxis()->SetTitleSize(0.06);
    rB->GetXaxis()->SetTitleOffset(1.15);
    rB->GetXaxis()->SetLabelSize(0.06);
    rB->GetXaxis()->SetRangeUser(0.0, 90.0);
    rB->GetXaxis()->SetNdivisions(6, 5, 0);
    rB->GetYaxis()->SetTitle("P (GeV)");
    rB->GetYaxis()->CenterTitle(true);
    rB->GetYaxis()->SetTitleSize(0.06);
    rB->GetYaxis()->SetTitleOffset(1.15);
    rB->GetYaxis()->SetLabelSize(0.06);
    rB->GetYaxis()->SetRangeUser(0.0, 2.0);
    rB->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    rB->SetTitle("proton from N-#phi");
    rB->DrawClone("axis");
    r0a->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf(", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r0b->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r0c->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");//
    rB->SetTitle("proton with N-#phi production");
    rB->DrawClone("axis");
    r1a->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r1b->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r1c->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");//
    rB->SetTitle("proton with #phi production");
    rB->DrawClone("axis");
    r2a->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{+} from #phi");
    rB->DrawClone("axis");
    r2b->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{-} from #phi");
    rB->DrawClone("axis");
    r2c->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");//
    rB->SetTitle("proton from #Lambda(1520)");
    rB->DrawClone("axis");
    r3a->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{+} with #Lambda(1520) production");
    rB->DrawClone("axis");
    r3b->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{-} from #Lambda(1520)");
    rB->DrawClone("axis");
    r3c->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");//
    rB->SetTitle("proton with direct KK production");
    rB->DrawClone("axis");
    r4a->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{+} from direct KK production");
    rB->DrawClone("axis");
    r4b->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf", "pdf");
    rB->SetTitle("K^{-} from direct KK production");
    rB->DrawClone("axis");
    r4c->Draw("colsame");
    c0->Print("gallary/PThetadetected.pdf)", "pdf");//
  }

  if (opt == 10){//invariant mass smeared 
    TFile * fs = new TFile("result/smeared.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h1 = (TH1D *) fs->Get("MpKK_BoundStateKK");
    TH1D * h2 = (TH1D *) fs->Get("MpKK_phi");
    TH1D * h3 = (TH1D *) fs->Get("MpKK_Lambda1520");
    TH1D * h4 = (TH1D *) fs->Get("MpKK_directKK");
    TH1D * h0a = (TH1D *) fs->Get("MpKp_BoundStateAll");
    TH1D * h1a = (TH1D *) fs->Get("MpKp_BoundStateKK");
    TH1D * h2a = (TH1D *) fs->Get("MpKp_phi");
    TH1D * h3a = (TH1D *) fs->Get("MpKp_Lambda1520");
    TH1D * h4a = (TH1D *) fs->Get("MpKp_directKK");
    TH1D * h0b = (TH1D *) fs->Get("MpKm_BoundStateAll");
    TH1D * h1b = (TH1D *) fs->Get("MpKm_BoundStateKK");
    TH1D * h2b = (TH1D *) fs->Get("MpKm_phi");
    TH1D * h3b = (TH1D *) fs->Get("MpKm_Lambda1520");
    TH1D * h4b = (TH1D *) fs->Get("MpKm_directKK");
    TH1D * h0c = (TH1D *) fs->Get("MKK_BoundStateAll");
    TH1D * h1c = (TH1D *) fs->Get("MKK_BoundStateKK");
    TH1D * h2c = (TH1D *) fs->Get("MKK_phi");
    TH1D * h3c = (TH1D *) fs->Get("MKK_Lambda1520");
    TH1D * h4c = (TH1D *) fs->Get("MKK_directKK");
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    double binsize = 0.2;//MeV
    h0->GetXaxis()->SetTitle("M(pKK) (GeV)");
    h0->GetXaxis()->CenterTitle(true);
    h0->GetXaxis()->SetTitleSize(0.06);
    h0->GetXaxis()->SetTitleOffset(1.15);
    h0->GetXaxis()->SetLabelSize(0.06);
    h0->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0->GetXaxis()->SetNdivisions(6, 5, 0);
    h0->GetYaxis()->SetTitle("counts / hour / MeV");
    h0->GetYaxis()->CenterTitle(true);
    h0->GetYaxis()->SetTitleSize(0.06);
    h0->GetYaxis()->SetTitleOffset(1.15);
    h0->GetYaxis()->SetLabelSize(0.06);
    h0->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0->GetYaxis()->SetNdivisions(5, 5, 0);
    h0a->GetXaxis()->SetTitle("M(pK^{+}) (GeV)");
    h0a->GetXaxis()->CenterTitle(true);
    h0a->GetXaxis()->SetTitleSize(0.06);
    h0a->GetXaxis()->SetTitleOffset(1.15);
    h0a->GetXaxis()->SetLabelSize(0.06);
    h0a->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0a->GetXaxis()->SetNdivisions(6, 5, 0);
    h0a->GetYaxis()->SetTitle("counts / hour / MeV");
    h0a->GetYaxis()->CenterTitle(true);
    h0a->GetYaxis()->SetTitleSize(0.06);
    h0a->GetYaxis()->SetTitleOffset(1.15);
    h0a->GetYaxis()->SetLabelSize(0.06);
    h0a->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0a->GetYaxis()->SetNdivisions(5, 5, 0);
    h0b->GetXaxis()->SetTitle("M(pK^{-}) (GeV)");
    h0b->GetXaxis()->CenterTitle(true);
    h0b->GetXaxis()->SetTitleSize(0.06);
    h0b->GetXaxis()->SetTitleOffset(1.15);
    h0b->GetXaxis()->SetLabelSize(0.06);
    h0b->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0b->GetXaxis()->SetNdivisions(6, 5, 0);
    h0b->GetYaxis()->SetTitle("counts / hour / MeV");
    h0b->GetYaxis()->CenterTitle(true);
    h0b->GetYaxis()->SetTitleSize(0.06);
    h0b->GetYaxis()->SetTitleOffset(1.15);
    h0b->GetYaxis()->SetLabelSize(0.06);
    h0b->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0b->GetYaxis()->SetNdivisions(5, 5, 0);
    h0c->GetXaxis()->SetTitle("M(K^{+}K^{-}) (GeV)");
    h0c->GetXaxis()->CenterTitle(true);
    h0c->GetXaxis()->SetTitleSize(0.06);
    h0c->GetXaxis()->SetTitleOffset(1.15);
    h0c->GetXaxis()->SetLabelSize(0.06);
    h0c->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0c->GetXaxis()->SetNdivisions(6, 5, 0);
    h0c->GetYaxis()->SetTitle("counts / hour / MeV");
    h0c->GetYaxis()->CenterTitle(true);
    h0c->GetYaxis()->SetTitleSize(0.06);
    h0c->GetYaxis()->SetTitleOffset(1.15);
    h0c->GetYaxis()->SetLabelSize(0.06);
    h0c->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    h0->Scale(lumi*time/binsize);
    h1->Scale(lumi*time/binsize);
    h2->Scale(lumi*time/binsize);
    h3->Scale(lumi*time/binsize);
    h4->Scale(lumi*time/binsize);
    h0a->Scale(lumi*time/binsize);
    h1a->Scale(lumi*time/binsize);
    h2a->Scale(lumi*time/binsize);
    h3a->Scale(lumi*time/binsize);
    h4a->Scale(lumi*time/binsize);
    h0b->Scale(lumi*time/binsize);
    h1b->Scale(lumi*time/binsize);
    h2b->Scale(lumi*time/binsize);
    h3b->Scale(lumi*time/binsize);
    h4b->Scale(lumi*time/binsize);
    h0c->Scale(lumi*time/binsize);
    h1c->Scale(lumi*time/binsize);
    h2c->Scale(lumi*time/binsize);
    h3c->Scale(lumi*time/binsize);
    h4c->Scale(lumi*time/binsize);
    //
    h0->SetStats(0);
    h0a->SetStats(0);
    h0b->SetStats(0);
    h0c->SetStats(0);
    //
    h0->SetLineColor(1);
    h1->SetLineColor(4);
    h2->SetLineColor(2);
    h3->SetLineColor(6);
    h4->SetLineColor(7);
    h0a->SetLineColor(1);
    h1a->SetLineColor(4);
    h2a->SetLineColor(2);
    h3a->SetLineColor(6);
    h4a->SetLineColor(7);
    h0b->SetLineColor(1);
    h1b->SetLineColor(4);
    h2b->SetLineColor(2);
    h3b->SetLineColor(6);
    h4b->SetLineColor(7);
    h0c->SetLineColor(1);
    h1c->SetLineColor(4);
    h2c->SetLineColor(2);
    h3c->SetLineColor(6);
    h4c->SetLineColor(7);
    //
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    h0->SetMaximum(0.15);
    h0->DrawClone("axis");
    h0->DrawClone("same");
    h1->DrawClone("same");
    h2->DrawClone("same");
    h3->DrawClone("same");
    h4->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Masssmeared.pdf(","pdf");//
    h0a->SetMaximum(0.1);
    h0a->DrawClone("axis");
    h0a->DrawClone("same");
    h1a->DrawClone("same");
    h2a->DrawClone("same");
    h3a->DrawClone("same");
    h4a->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Masssmeared.pdf","pdf");//
    h0b->SetMaximum(0.1);
    h0b->DrawClone("axis");
    h0b->DrawClone("same");
    h1b->DrawClone("same");
    h2b->DrawClone("same");
    h3b->Scale(1/20.);h3b->DrawClone("same");
    h4b->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production / 20", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Masssmeared.pdf","pdf");//
    h0c->SetMaximum(0.1);
    h0c->DrawClone("axis");
    h0c->DrawClone("same");
    h1c->DrawClone("same");
    h2c->Scale(1/20.);h2c->DrawClone("same");
    h3c->DrawClone("same");
    h4c->DrawClone("same");
    h0c->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production / 20", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Masssmeared.pdf)","pdf");
  }

  if (opt == 11){//Momentum smeared
    TFile * fs = new TFile("result/smeared.root", "r");
    TH2D * d0a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateAll");
    TH2D * d1a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateKK");
    TH2D * d2a = (TH2D *) fs->Get("Momentum_p_Kp_phi");
    TH2D * d3a = (TH2D *) fs->Get("Momentum_p_Kp_Lambda1520");
    TH2D * d4a = (TH2D *) fs->Get("Momentum_p_Kp_KK");
    TH2D * d0b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateAll");
    TH2D * d1b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateKK");
    TH2D * d2b = (TH2D *) fs->Get("Momentum_p_Km_phi");
    TH2D * d3b = (TH2D *) fs->Get("Momentum_p_Km_Lambda1520");
    TH2D * d4b = (TH2D *) fs->Get("Momentum_p_Km_KK");
    TH2D * d0c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateAll");
    TH2D * d1c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateKK");
    TH2D * d2c = (TH2D *) fs->Get("Momentum_Kp_Km_phi");
    TH2D * d3c = (TH2D *) fs->Get("Momentum_Kp_Km_Lambda1520");
    TH2D * d4c = (TH2D *) fs->Get("Momentum_Kp_Km_KK");
    TGraph * g0a = new TGraph(1000);
    TGraph * g1a = new TGraph(1000);
    TGraph * g2a = new TGraph(1000);
    TGraph * g3a = new TGraph(1000);
    TGraph * g4a = new TGraph(1000);
    TGraph * g0b = new TGraph(1000);
    TGraph * g1b = new TGraph(1000);
    TGraph * g2b = new TGraph(1000);
    TGraph * g3b = new TGraph(1000);
    TGraph * g4b = new TGraph(1000);
    TGraph * g0c = new TGraph(1000);
    TGraph * g1c = new TGraph(1000);
    TGraph * g2c = new TGraph(1000);
    TGraph * g3c = new TGraph(1000);
    TGraph * g4c = new TGraph(1000);
    double x, y;
    for (int i = 0; i < 1000; i++){
      d0a->GetRandom2(x, y);
      g0a->SetPoint(i, x, y);
      d1a->GetRandom2(x, y);
      g1a->SetPoint(i, x, y);
      d2a->GetRandom2(x, y);
      g2a->SetPoint(i, x, y);
      d3a->GetRandom2(x, y);
      g3a->SetPoint(i, x, y);
      d4a->GetRandom2(x, y);
      g4a->SetPoint(i, x, y);
      d0b->GetRandom2(x, y);
      g0b->SetPoint(i, x, y);
      d1b->GetRandom2(x, y);
      g1b->SetPoint(i, x, y);
      d2b->GetRandom2(x, y);
      g2b->SetPoint(i, x, y);
      d3b->GetRandom2(x, y);
      g3b->SetPoint(i, x, y);
      d4b->GetRandom2(x, y);
      g4b->SetPoint(i, x, y);
      d0c->GetRandom2(x, y);
      g0c->SetPoint(i, x, y);
      d1c->GetRandom2(x, y);
      g1c->SetPoint(i, x, y);
      d2c->GetRandom2(x, y);
      g2c->SetPoint(i, x, y);
      d3c->GetRandom2(x, y);
      g3c->SetPoint(i, x, y);
      d4c->GetRandom2(x, y);
      g4c->SetPoint(i, x, y);
    }
    //
    d0a->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0a->GetXaxis()->CenterTitle(true);
    d0a->GetXaxis()->SetTitleSize(0.06);
    d0a->GetXaxis()->SetTitleOffset(1.15);
    d0a->GetXaxis()->SetLabelSize(0.06);
    d0a->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetXaxis()->SetNdivisions(6, 5, 0);
    d0a->GetYaxis()->SetTitle("P(p) (GeV)");
    d0a->GetYaxis()->CenterTitle(true);
    d0a->GetYaxis()->SetTitleSize(0.06);
    d0a->GetYaxis()->SetTitleOffset(1.15);
    d0a->GetYaxis()->SetLabelSize(0.06);
    d0a->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetYaxis()->SetNdivisions(5, 5, 0);
    d0b->GetXaxis()->SetTitle("P(K^{-}) (GeV)");
    d0b->GetXaxis()->CenterTitle(true);
    d0b->GetXaxis()->SetTitleSize(0.06);
    d0b->GetXaxis()->SetTitleOffset(1.15);
    d0b->GetXaxis()->SetLabelSize(0.06);
    d0b->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetXaxis()->SetNdivisions(6, 5, 0);
    d0b->GetYaxis()->SetTitle("P(p) (GeV)");
    d0b->GetYaxis()->CenterTitle(true);
    d0b->GetYaxis()->SetTitleSize(0.06);
    d0b->GetYaxis()->SetTitleOffset(1.15);
    d0b->GetYaxis()->SetLabelSize(0.06);
    d0b->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetYaxis()->SetNdivisions(5, 5, 0);
    d0c->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0c->GetXaxis()->CenterTitle(true);
    d0c->GetXaxis()->SetTitleSize(0.06);
    d0c->GetXaxis()->SetTitleOffset(1.15);
    d0c->GetXaxis()->SetLabelSize(0.06);
    d0c->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetXaxis()->SetNdivisions(6, 5, 0);
    d0c->GetYaxis()->SetTitle("P(K^{-}) (GeV)");
    d0c->GetYaxis()->CenterTitle(true);
    d0c->GetYaxis()->SetTitleSize(0.06);
    d0c->GetYaxis()->SetTitleOffset(1.15);
    d0c->GetYaxis()->SetLabelSize(0.06);
    d0c->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    d0a->SetStats(0);
    d0b->SetStats(0);
    d0c->SetStats(0);
    //
    g0a->SetMarkerStyle(20);
    g0a->SetMarkerColor(1);
    g0a->SetMarkerSize(0.6);
    g1a->SetMarkerStyle(21);
    g1a->SetMarkerColor(4);
    g1a->SetMarkerSize(0.6);
    g2a->SetMarkerStyle(22);
    g2a->SetMarkerColor(2);
    g2a->SetMarkerSize(0.6);
    g3a->SetMarkerStyle(23);
    g3a->SetMarkerColor(6);
    g3a->SetMarkerSize(0.6);
    g4a->SetMarkerStyle(25);
    g4a->SetMarkerColor(7);
    g4a->SetMarkerSize(0.6);
    g0b->SetMarkerStyle(20);
    g0b->SetMarkerColor(1);
    g0b->SetMarkerSize(0.6);
    g1b->SetMarkerStyle(21);
    g1b->SetMarkerColor(4);
    g1b->SetMarkerSize(0.6);
    g2b->SetMarkerStyle(22);
    g2b->SetMarkerColor(2);
    g2b->SetMarkerSize(0.6);
    g3b->SetMarkerStyle(23);
    g3b->SetMarkerColor(6);
    g3b->SetMarkerSize(0.6);
    g4b->SetMarkerStyle(25);
    g4b->SetMarkerColor(7);
    g4b->SetMarkerSize(0.6);
    g0c->SetMarkerStyle(20);
    g0c->SetMarkerColor(1);
    g0c->SetMarkerSize(0.6);
    g1c->SetMarkerStyle(21);
    g1c->SetMarkerColor(4);
    g1c->SetMarkerSize(0.6);
    g2c->SetMarkerStyle(22);
    g2c->SetMarkerColor(2);
    g2c->SetMarkerSize(0.6);
    g3c->SetMarkerStyle(23);
    g3c->SetMarkerColor(6);
    g3c->SetMarkerSize(0.6);
    g4c->SetMarkerStyle(25);
    g4c->SetMarkerColor(7);
    g4c->SetMarkerSize(0.6);
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(g0a, "pKK from N-#phi", "p");
    leg->AddEntry(g1a, "only KK from N-#phi", "p");
    leg->AddEntry(g2a, "#phi production", "p");
    leg->AddEntry(g3a, "#Lambda(1520) production", "p");
    leg->AddEntry(g4a, "direct KK production", "p");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    //
    d0a->DrawClone("axis");
    g0a->DrawClone("psame");
    g1a->DrawClone("psame");
    g2a->DrawClone("psame");
    g3a->DrawClone("psame");
    g4a->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumsmeared.pdf(","pdf");//
    d0a->SetTitle("pKK from N-#phi");
    d0a->DrawClone("axis");
    d0a->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0a->SetTitle("only KK from N-#phi");
    d0a->DrawClone("axis");
    d1a->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0a->SetTitle("#phi production");
    d0a->DrawClone("axis");
    d2a->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0a->SetTitle("#Lambda(1520) production");
    d0a->DrawClone("axis");
    d3a->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//    
    d0a->SetTitle("direct KK production");
    d0a->DrawClone("axis");
    d4a->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    //
    d0b->DrawClone("axis");
    g0b->DrawClone("psame");
    g1b->DrawClone("psame");
    g2b->DrawClone("psame");
    g3b->DrawClone("psame");
    g4b->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumsmeared.pdf(","pdf");//
    d0b->SetTitle("pKK from N-#phi");
    d0b->DrawClone("axis");
    d0b->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0b->SetTitle("only KK from N-#phi");
    d0b->DrawClone("axis");
    d1b->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0b->SetTitle("#phi production");
    d0b->DrawClone("axis");
    d2b->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0b->SetTitle("#Lambda(1520) production");
    d0b->DrawClone("axis");
    d3b->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//    
    d0b->SetTitle("direct KK production");
    d0b->DrawClone("axis");
    d4b->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    //
    d0c->DrawClone("axis");
    g0c->DrawClone("psame");
    g1c->DrawClone("psame");
    g2c->DrawClone("psame");
    g3c->DrawClone("psame");
    g4c->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumsmeared.pdf(","pdf");//
    d0c->SetTitle("pKK from N-#phi");
    d0c->DrawClone("axis");
    d0c->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0c->SetTitle("only KK from N-#phi");
    d0c->DrawClone("axis");
    d1c->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0c->SetTitle("#phi production");
    d0c->DrawClone("axis");
    d2c->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//
    d0c->SetTitle("#Lambda(1520) production");
    d0c->DrawClone("axis");
    d3c->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf","pdf");//    
    d0c->SetTitle("direct KK production");
    d0c->DrawClone("axis");
    d4c->DrawClone("colsame");
    c0->Print("gallary/Momentumsmeared.pdf)","pdf");//
  }

  if (opt == 12){//P-theta smeared
    //gStyle->SetPalette(52);
    TFile * fs = new TFile("result/smeared.root", "r");
    TH2D * r0a = (TH2D *) fs->Get("PTheta_p_BoundStateAll");
    TH2D * r0b = (TH2D *) fs->Get("PTheta_Kp_BoundStateAll");
    TH2D * r0c = (TH2D *) fs->Get("PTheta_Km_BoundStateAll");
    TH2D * r1a = (TH2D *) fs->Get("PTheta_p_BoundStateKK");
    TH2D * r1b = (TH2D *) fs->Get("PTheta_Kp_BoundStateKK");
    TH2D * r1c = (TH2D *) fs->Get("PTheta_Km_BoundStateKK");
    TH2D * r2a = (TH2D *) fs->Get("PTheta_p_phi");
    TH2D * r2b = (TH2D *) fs->Get("PTheta_Kp_phi");
    TH2D * r2c = (TH2D *) fs->Get("PTheta_Km_phi");
    TH2D * r3a = (TH2D *) fs->Get("PTheta_p_Lambda1520");
    TH2D * r3b = (TH2D *) fs->Get("PTheta_Kp_Lambda1520");
    TH2D * r3c = (TH2D *) fs->Get("PTheta_Km_Lambda1520");
    TH2D * r4a = (TH2D *) fs->Get("PTheta_p_KK");
    TH2D * r4b = (TH2D *) fs->Get("PTheta_Kp_KK");
    TH2D * r4c = (TH2D *) fs->Get("PTheta_Km_KK");
    TH2D * rB = new TH2D("rB", "", 1, 0.0, 90.0, 1, 0.0, 2.0);
    rB->SetStats(0);
    rB->GetXaxis()->SetTitle("#theta (deg)");
    rB->GetXaxis()->CenterTitle(true);
    rB->GetXaxis()->SetTitleSize(0.06);
    rB->GetXaxis()->SetTitleOffset(1.15);
    rB->GetXaxis()->SetLabelSize(0.06);
    rB->GetXaxis()->SetRangeUser(0.0, 90.0);
    rB->GetXaxis()->SetNdivisions(6, 5, 0);
    rB->GetYaxis()->SetTitle("P (GeV)");
    rB->GetYaxis()->CenterTitle(true);
    rB->GetYaxis()->SetTitleSize(0.06);
    rB->GetYaxis()->SetTitleOffset(1.15);
    rB->GetYaxis()->SetLabelSize(0.06);
    rB->GetYaxis()->SetRangeUser(0.0, 2.0);
    rB->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    rB->SetTitle("proton from N-#phi");
    rB->DrawClone("axis");
    r0a->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf(", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r0b->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r0c->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");//
    rB->SetTitle("proton with N-#phi production");
    rB->DrawClone("axis");
    r1a->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r1b->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r1c->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");//
    rB->SetTitle("proton with #phi production");
    rB->DrawClone("axis");
    r2a->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{+} from #phi");
    rB->DrawClone("axis");
    r2b->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{-} from #phi");
    rB->DrawClone("axis");
    r2c->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");//
    rB->SetTitle("proton from #Lambda(1520)");
    rB->DrawClone("axis");
    r3a->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{+} with #Lambda(1520) production");
    rB->DrawClone("axis");
    r3b->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{-} from #Lambda(1520)");
    rB->DrawClone("axis");
    r3c->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");//
    rB->SetTitle("proton with direct KK production");
    rB->DrawClone("axis");
    r4a->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{+} from direct KK production");
    rB->DrawClone("axis");
    r4b->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf", "pdf");
    rB->SetTitle("K^{-} from direct KK production");
    rB->DrawClone("axis");
    r4c->Draw("colsame");
    c0->Print("gallary/PThetasmeared.pdf)", "pdf");//
  }

  if (opt == 13){//Two pions
    TFile * fs = new TFile("result/cut.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h0a = (TH1D *) fs->Get("MpKp_BoundStateAll");
    TH1D * h0b = (TH1D *) fs->Get("MpKm_BoundStateAll");
    TH1D * h0c = (TH1D *) fs->Get("MKK_BoundStateAll");
    TH1D * h1 = (TH1D *) fs->Get("MpKK_PiPi");
    TH1D * h1a = (TH1D *) fs->Get("MpKp_PiPi");
    TH1D * h1b = (TH1D *) fs->Get("MpKm_PiPi");
    TH1D * h1c = (TH1D *) fs->Get("MKK_PiPi");
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    double binsize = 0.2;//MeV
    h0->GetXaxis()->SetTitle("M(pKK) (GeV)");
    h0->GetXaxis()->CenterTitle(true);
    h0->GetXaxis()->SetTitleSize(0.06);
    h0->GetXaxis()->SetTitleOffset(1.15);
    h0->GetXaxis()->SetLabelSize(0.06);
    h0->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0->GetXaxis()->SetNdivisions(6, 5, 0);
    h0->GetYaxis()->SetTitle("counts / hour / MeV");
    h0->GetYaxis()->CenterTitle(true);
    h0->GetYaxis()->SetTitleSize(0.06);
    h0->GetYaxis()->SetTitleOffset(1.15);
    h0->GetYaxis()->SetLabelSize(0.06);
    h0->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0->GetYaxis()->SetNdivisions(5, 5, 0);
    h0a->GetXaxis()->SetTitle("M(pK^{+}) (GeV)");
    h0a->GetXaxis()->CenterTitle(true);
    h0a->GetXaxis()->SetTitleSize(0.06);
    h0a->GetXaxis()->SetTitleOffset(1.15);
    h0a->GetXaxis()->SetLabelSize(0.06);
    h0a->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0a->GetXaxis()->SetNdivisions(6, 5, 0);
    h0a->GetYaxis()->SetTitle("counts / hour / MeV");
    h0a->GetYaxis()->CenterTitle(true);
    h0a->GetYaxis()->SetTitleSize(0.06);
    h0a->GetYaxis()->SetTitleOffset(1.15);
    h0a->GetYaxis()->SetLabelSize(0.06);
    h0a->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0a->GetYaxis()->SetNdivisions(5, 5, 0);
    h0b->GetXaxis()->SetTitle("M(pK^{-}) (GeV)");
    h0b->GetXaxis()->CenterTitle(true);
    h0b->GetXaxis()->SetTitleSize(0.06);
    h0b->GetXaxis()->SetTitleOffset(1.15);
    h0b->GetXaxis()->SetLabelSize(0.06);
    h0b->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0b->GetXaxis()->SetNdivisions(6, 5, 0);
    h0b->GetYaxis()->SetTitle("counts / hour / MeV");
    h0b->GetYaxis()->CenterTitle(true);
    h0b->GetYaxis()->SetTitleSize(0.06);
    h0b->GetYaxis()->SetTitleOffset(1.15);
    h0b->GetYaxis()->SetLabelSize(0.06);
    h0b->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0b->GetYaxis()->SetNdivisions(5, 5, 0);
    h0c->GetXaxis()->SetTitle("M(K^{+}K^{-}) (GeV)");
    h0c->GetXaxis()->CenterTitle(true);
    h0c->GetXaxis()->SetTitleSize(0.06);
    h0c->GetXaxis()->SetTitleOffset(1.15);
    h0c->GetXaxis()->SetLabelSize(0.06);
    h0c->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0c->GetXaxis()->SetNdivisions(6, 5, 0);
    h0c->GetYaxis()->SetTitle("counts / hour / MeV");
    h0c->GetYaxis()->CenterTitle(true);
    h0c->GetYaxis()->SetTitleSize(0.06);
    h0c->GetYaxis()->SetTitleOffset(1.15);
    h0c->GetYaxis()->SetLabelSize(0.06);
    h0c->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    h0->Scale(lumi*time/binsize);
    h1->Scale(lumi*time/binsize);
    h0a->Scale(lumi*time/binsize);
    h1a->Scale(lumi*time/binsize);
    h0b->Scale(lumi*time/binsize);
    h1b->Scale(lumi*time/binsize);
    h0c->Scale(lumi*time/binsize);
    h1c->Scale(lumi*time/binsize);
    //
    h0->SetStats(0);
    h0a->SetStats(0);
    h0b->SetStats(0);
    h0c->SetStats(0);
    //
    h0->SetLineColor(1);
    h1->SetLineColor(2);
    h0a->SetLineColor(1);
    h1a->SetLineColor(2);
    h0b->SetLineColor(1);
    h1b->SetLineColor(2);
    h0c->SetLineColor(1);
    h1c->SetLineColor(2);
    //
    h1->Scale(0.01);
    h1a->Scale(0.01);
    h1b->Scale(0.01);
    h1c->Scale(0.01);
    //
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "2#pi misidentified", "l");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    h0->SetMaximum(0.3);
    h0->GetXaxis()->SetRangeUser(1.91, 2.05);
    h0->DrawClone("axis");
    h0->DrawClone("same");
    h1->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPions.pdf(","pdf");//
    h0a->SetMaximum(0.3);
    h0a->GetXaxis()->SetRangeUser(1.4, 1.5);
    h0a->DrawClone("axis");
    h0a->DrawClone("same");
    h1a->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPions.pdf","pdf");//
    h0b->SetMaximum(0.3);
    h0b->GetXaxis()->SetRangeUser(1.4, 1.5);
    h0b->DrawClone("axis");
    h0b->DrawClone("same");
    h1b->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPions.pdf","pdf");//
    h0c->SetMaximum(0.3);
    h0c->GetXaxis()->SetRangeUser(0.98, 1.05);
    h0c->DrawClone("axis");
    h0c->DrawClone("same");
    h1c->DrawClone("same");
    h0c->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPions.pdf)","pdf");
  }

  if (opt == 131){//Two pions new
    TFile * fs = new TFile("result/cut.root", "r");
    TFile * f2pi = new TFile("result/twopinew.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h0a = (TH1D *) fs->Get("MpKp_BoundStateAll");
    TH1D * h0b = (TH1D *) fs->Get("MpKm_BoundStateAll");
    TH1D * h0c = (TH1D *) fs->Get("MKK_BoundStateAll");
    TH1D * h1 = (TH1D *) f2pi->Get("MpKK_TwoPi");
    TH1D * h1a = (TH1D *) f2pi->Get("MpKp_TwoPi");
    TH1D * h1b = (TH1D *) f2pi->Get("MpKm_TwoPi");
    TH1D * h1c = (TH1D *) f2pi->Get("MKK_TwoPi");
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    double binsize = 0.2;//MeV
    h0->GetXaxis()->SetTitle("M(pKK) (GeV)");
    h0->GetXaxis()->CenterTitle(true);
    h0->GetXaxis()->SetTitleSize(0.06);
    h0->GetXaxis()->SetTitleOffset(1.15);
    h0->GetXaxis()->SetLabelSize(0.06);
    h0->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0->GetXaxis()->SetNdivisions(6, 5, 0);
    h0->GetYaxis()->SetTitle("counts / hour / MeV");
    h0->GetYaxis()->CenterTitle(true);
    h0->GetYaxis()->SetTitleSize(0.06);
    h0->GetYaxis()->SetTitleOffset(1.15);
    h0->GetYaxis()->SetLabelSize(0.06);
    h0->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0->GetYaxis()->SetNdivisions(5, 5, 0);
    h0a->GetXaxis()->SetTitle("M(pK^{+}) (GeV)");
    h0a->GetXaxis()->CenterTitle(true);
    h0a->GetXaxis()->SetTitleSize(0.06);
    h0a->GetXaxis()->SetTitleOffset(1.15);
    h0a->GetXaxis()->SetLabelSize(0.06);
    h0a->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0a->GetXaxis()->SetNdivisions(6, 5, 0);
    h0a->GetYaxis()->SetTitle("counts / hour / MeV");
    h0a->GetYaxis()->CenterTitle(true);
    h0a->GetYaxis()->SetTitleSize(0.06);
    h0a->GetYaxis()->SetTitleOffset(1.15);
    h0a->GetYaxis()->SetLabelSize(0.06);
    h0a->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0a->GetYaxis()->SetNdivisions(5, 5, 0);
    h0b->GetXaxis()->SetTitle("M(pK^{-}) (GeV)");
    h0b->GetXaxis()->CenterTitle(true);
    h0b->GetXaxis()->SetTitleSize(0.06);
    h0b->GetXaxis()->SetTitleOffset(1.15);
    h0b->GetXaxis()->SetLabelSize(0.06);
    h0b->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0b->GetXaxis()->SetNdivisions(6, 5, 0);
    h0b->GetYaxis()->SetTitle("counts / hour / MeV");
    h0b->GetYaxis()->CenterTitle(true);
    h0b->GetYaxis()->SetTitleSize(0.06);
    h0b->GetYaxis()->SetTitleOffset(1.15);
    h0b->GetYaxis()->SetLabelSize(0.06);
    h0b->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0b->GetYaxis()->SetNdivisions(5, 5, 0);
    h0c->GetXaxis()->SetTitle("M(K^{+}K^{-}) (GeV)");
    h0c->GetXaxis()->CenterTitle(true);
    h0c->GetXaxis()->SetTitleSize(0.06);
    h0c->GetXaxis()->SetTitleOffset(1.15);
    h0c->GetXaxis()->SetLabelSize(0.06);
    h0c->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0c->GetXaxis()->SetNdivisions(6, 5, 0);
    h0c->GetYaxis()->SetTitle("counts / hour / MeV");
    h0c->GetYaxis()->CenterTitle(true);
    h0c->GetYaxis()->SetTitleSize(0.06);
    h0c->GetYaxis()->SetTitleOffset(1.15);
    h0c->GetYaxis()->SetLabelSize(0.06);
    h0c->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    h0->Scale(lumi*time/binsize);
    h1->Scale(time/binsize/10000/5e7);
    h0a->Scale(lumi*time/binsize);
    h1a->Scale(time/binsize/10000/5e7);
    h0b->Scale(lumi*time/binsize);
    h1b->Scale(time/binsize/10000/5e7);
    h0c->Scale(lumi*time/binsize);
    h1c->Scale(time/binsize/10000/5e7);
    //
    h0->SetStats(0);
    h0a->SetStats(0);
    h0b->SetStats(0);
    h0c->SetStats(0);
    //
    h0->SetLineColor(1);
    h1->SetLineColor(2);
    h0a->SetLineColor(1);
    h1a->SetLineColor(2);
    h0b->SetLineColor(1);
    h1b->SetLineColor(2);
    h0c->SetLineColor(1);
    h1c->SetLineColor(2);
    //
    h1->Scale(0.01);
    h1a->Scale(0.01);
    h1b->Scale(0.01);
    h1c->Scale(0.01);
    //
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "2#pi misidentified", "l");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    h0->SetMaximum(0.3);
    h0->GetXaxis()->SetRangeUser(1.91, 2.05);
    h0->DrawClone("axis");
    h0->DrawClone("same");
    h1->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPionsNew.pdf(","pdf");//
    h0a->SetMaximum(0.3);
    h0a->GetXaxis()->SetRangeUser(1.4, 1.5);
    h0a->DrawClone("axis");
    h0a->DrawClone("same");
    h1a->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPionsNew.pdf","pdf");//
    h0b->SetMaximum(0.3);
    h0b->GetXaxis()->SetRangeUser(1.4, 1.5);
    h0b->DrawClone("axis");
    h0b->DrawClone("same");
    h1b->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPionsNew.pdf","pdf");//
    h0c->SetMaximum(0.3);
    h0c->GetXaxis()->SetRangeUser(0.98, 1.05);
    h0c->DrawClone("axis");
    h0c->DrawClone("same");
    h1c->DrawClone("same");
    h0c->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/TwoPionsNew.pdf)","pdf");
  }

  if (opt == 14){//
    TFile * fs = new TFile("result/cut.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h1 = (TH1D *) fs->Get("MpKK_BoundStateKK");
    TH1D * h2 = (TH1D *) fs->Get("MpKK_phi");
    TH1D * h3 = (TH1D *) fs->Get("MpKK_Lambda1520");
    TH1D * h4 = (TH1D *) fs->Get("MpKK_directKK");
    TH1D * h5 = (TH1D *) fs->Get("MpKK_PiPi");
    h5->Scale(0.01);
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    int bin1 = h0->FindBin(1.935 + 1.0e-10);
    int bin2 = h0->FindBin(1.965 - 1.0e-10);
    cout << "Signal: " << h0->Integral(bin1, bin2) * lumi * time << endl;
    cout << "Back1:  " << h1->Integral(bin1, bin2) * lumi * time << endl;
    cout << "Back2:  " << h2->Integral(bin1, bin2) * lumi * time << endl;
    cout << "Back3:  " << h3->Integral(bin1, bin2) * lumi * time << endl;
    cout << "Back4:  " << h4->Integral(bin1, bin2) * lumi * time << endl;
    cout << "Back5:  " << h5->Integral(bin1, bin2) * lumi * time << endl;
  }

  if (opt == 15){//invariant mass cut
    TFile * fs = new TFile("result/cut.root", "r");
    TH1D * h0 = (TH1D *) fs->Get("MpKK_BoundStateAll");
    TH1D * h1 = (TH1D *) fs->Get("MpKK_BoundStateKK");
    TH1D * h2 = (TH1D *) fs->Get("MpKK_phi");
    TH1D * h3 = (TH1D *) fs->Get("MpKK_Lambda1520");
    TH1D * h4 = (TH1D *) fs->Get("MpKK_directKK");
    TH1D * h0a = (TH1D *) fs->Get("MpKp_BoundStateAll");
    TH1D * h1a = (TH1D *) fs->Get("MpKp_BoundStateKK");
    TH1D * h2a = (TH1D *) fs->Get("MpKp_phi");
    TH1D * h3a = (TH1D *) fs->Get("MpKp_Lambda1520");
    TH1D * h4a = (TH1D *) fs->Get("MpKp_directKK");
    TH1D * h0b = (TH1D *) fs->Get("MpKm_BoundStateAll");
    TH1D * h1b = (TH1D *) fs->Get("MpKm_BoundStateKK");
    TH1D * h2b = (TH1D *) fs->Get("MpKm_phi");
    TH1D * h3b = (TH1D *) fs->Get("MpKm_Lambda1520");
    TH1D * h4b = (TH1D *) fs->Get("MpKm_directKK");
    TH1D * h0c = (TH1D *) fs->Get("MKK_BoundStateAll");
    TH1D * h1c = (TH1D *) fs->Get("MKK_BoundStateKK");
    TH1D * h2c = (TH1D *) fs->Get("MKK_phi");
    TH1D * h3c = (TH1D *) fs->Get("MKK_Lambda1520");
    TH1D * h4c = (TH1D *) fs->Get("MKK_directKK");
    double lumi = 1.0e35 * 1.0e-26 * pow(Phys::hbar, 2) / GOLD::NA;//eA GeV^2 s^-1
    double time = 3600.0;
    double binsize = 0.2;//MeV
    h0->GetXaxis()->SetTitle("M(pKK) (GeV)");
    h0->GetXaxis()->CenterTitle(true);
    h0->GetXaxis()->SetTitleSize(0.06);
    h0->GetXaxis()->SetTitleOffset(1.15);
    h0->GetXaxis()->SetLabelSize(0.06);
    h0->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0->GetXaxis()->SetNdivisions(6, 5, 0);
    h0->GetYaxis()->SetTitle("counts / hour / MeV");
    h0->GetYaxis()->CenterTitle(true);
    h0->GetYaxis()->SetTitleSize(0.06);
    h0->GetYaxis()->SetTitleOffset(1.15);
    h0->GetYaxis()->SetLabelSize(0.06);
    h0->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0->GetYaxis()->SetNdivisions(5, 5, 0);
    h0a->GetXaxis()->SetTitle("M(pK^{+}) (GeV)");
    h0a->GetXaxis()->CenterTitle(true);
    h0a->GetXaxis()->SetTitleSize(0.06);
    h0a->GetXaxis()->SetTitleOffset(1.15);
    h0a->GetXaxis()->SetLabelSize(0.06);
    h0a->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0a->GetXaxis()->SetNdivisions(6, 5, 0);
    h0a->GetYaxis()->SetTitle("counts / hour / MeV");
    h0a->GetYaxis()->CenterTitle(true);
    h0a->GetYaxis()->SetTitleSize(0.06);
    h0a->GetYaxis()->SetTitleOffset(1.15);
    h0a->GetYaxis()->SetLabelSize(0.06);
    h0a->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0a->GetYaxis()->SetNdivisions(5, 5, 0);
    h0b->GetXaxis()->SetTitle("M(pK^{-}) (GeV)");
    h0b->GetXaxis()->CenterTitle(true);
    h0b->GetXaxis()->SetTitleSize(0.06);
    h0b->GetXaxis()->SetTitleOffset(1.15);
    h0b->GetXaxis()->SetLabelSize(0.06);
    h0b->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0b->GetXaxis()->SetNdivisions(6, 5, 0);
    h0b->GetYaxis()->SetTitle("counts / hour / MeV");
    h0b->GetYaxis()->CenterTitle(true);
    h0b->GetYaxis()->SetTitleSize(0.06);
    h0b->GetYaxis()->SetTitleOffset(1.15);
    h0b->GetYaxis()->SetLabelSize(0.06);
    h0b->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0b->GetYaxis()->SetNdivisions(5, 5, 0);
    h0c->GetXaxis()->SetTitle("M(K^{+}K^{-}) (GeV)");
    h0c->GetXaxis()->CenterTitle(true);
    h0c->GetXaxis()->SetTitleSize(0.06);
    h0c->GetXaxis()->SetTitleOffset(1.15);
    h0c->GetXaxis()->SetLabelSize(0.06);
    h0c->GetXaxis()->SetRangeUser(1.88, 2.32);
    h0c->GetXaxis()->SetNdivisions(6, 5, 0);
    h0c->GetYaxis()->SetTitle("counts / hour / MeV");
    h0c->GetYaxis()->CenterTitle(true);
    h0c->GetYaxis()->SetTitleSize(0.06);
    h0c->GetYaxis()->SetTitleOffset(1.15);
    h0c->GetYaxis()->SetLabelSize(0.06);
    h0c->GetYaxis()->SetRangeUser(0.0, 15.0);
    h0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    h0->Scale(lumi*time/binsize);
    h1->Scale(lumi*time/binsize);
    h2->Scale(lumi*time/binsize);
    h3->Scale(lumi*time/binsize);
    h4->Scale(lumi*time/binsize);
    h0a->Scale(lumi*time/binsize);
    h1a->Scale(lumi*time/binsize);
    h2a->Scale(lumi*time/binsize);
    h3a->Scale(lumi*time/binsize);
    h4a->Scale(lumi*time/binsize);
    h0b->Scale(lumi*time/binsize);
    h1b->Scale(lumi*time/binsize);
    h2b->Scale(lumi*time/binsize);
    h3b->Scale(lumi*time/binsize);
    h4b->Scale(lumi*time/binsize);
    h0c->Scale(lumi*time/binsize);
    h1c->Scale(lumi*time/binsize);
    h2c->Scale(lumi*time/binsize);
    h3c->Scale(lumi*time/binsize);
    h4c->Scale(lumi*time/binsize);
    //
    h0->SetStats(0);
    h0a->SetStats(0);
    h0b->SetStats(0);
    h0c->SetStats(0);
    //
    h0->SetLineColor(1);
    h1->SetLineColor(4);
    h2->SetLineColor(2);
    h3->SetLineColor(6);
    h4->SetLineColor(7);
    h0a->SetLineColor(1);
    h1a->SetLineColor(4);
    h2a->SetLineColor(2);
    h3a->SetLineColor(6);
    h4a->SetLineColor(7);
    h0b->SetLineColor(1);
    h1b->SetLineColor(4);
    h2b->SetLineColor(2);
    h3b->SetLineColor(6);
    h4b->SetLineColor(7);
    h0c->SetLineColor(1);
    h1c->SetLineColor(4);
    h2c->SetLineColor(2);
    h3c->SetLineColor(6);
    h4c->SetLineColor(7);
    //
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    h0->SetMaximum(0.15);
    h0->DrawClone("axis");
    h0->DrawClone("same");
    h1->DrawClone("same");
    h2->DrawClone("same");
    h3->DrawClone("same");
    h4->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Masscut.pdf(","pdf");//
    h0a->SetMaximum(0.1);
    h0a->DrawClone("axis");
    h0a->DrawClone("same");
    h1a->DrawClone("same");
    h2a->DrawClone("same");
    h3a->DrawClone("same");
    h4a->DrawClone("same");
    leg->DrawClone("same");
    c0->Print("gallary/Masscut.pdf","pdf");//
    h0b->SetMaximum(0.1);
    h0b->DrawClone("axis");
    h0b->DrawClone("same");
    h1b->DrawClone("same");
    h2b->DrawClone("same");
    h3b->Scale(1/20.);h3b->DrawClone("same");
    h4b->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production", "l");
    leg->AddEntry(h3, "#Lambda(1520) production / 20", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Masscut.pdf","pdf");//
    h0c->SetMaximum(0.1);
    h0c->DrawClone("axis");
    h0c->DrawClone("same");
    h1c->DrawClone("same");
    h2c->Scale(1/20.);h2c->DrawClone("same");
    h3c->DrawClone("same");
    h4c->DrawClone("same");
    h0c->DrawClone("same");
    leg->Clear();
    leg->AddEntry(h0, "pKK from N-#phi", "l");
    leg->AddEntry(h1, "only KK from N-#phi", "l");
    leg->AddEntry(h2, "#phi production / 20", "l");
    leg->AddEntry(h3, "#Lambda(1520) production", "l");
    leg->AddEntry(h4, "direct KK production", "l");
    leg->DrawClone("same");
    c0->Print("gallary/Masscut.pdf)","pdf");
  }

  if (opt == 16){//Momentum cut
    TFile * fs = new TFile("result/cut.root", "r");
    TH2D * d0a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateAll");
    TH2D * d1a = (TH2D *) fs->Get("Momentum_p_Kp_BoundStateKK");
    TH2D * d2a = (TH2D *) fs->Get("Momentum_p_Kp_phi");
    TH2D * d3a = (TH2D *) fs->Get("Momentum_p_Kp_Lambda1520");
    TH2D * d4a = (TH2D *) fs->Get("Momentum_p_Kp_KK");
    TH2D * d0b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateAll");
    TH2D * d1b = (TH2D *) fs->Get("Momentum_p_Km_BoundStateKK");
    TH2D * d2b = (TH2D *) fs->Get("Momentum_p_Km_phi");
    TH2D * d3b = (TH2D *) fs->Get("Momentum_p_Km_Lambda1520");
    TH2D * d4b = (TH2D *) fs->Get("Momentum_p_Km_KK");
    TH2D * d0c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateAll");
    TH2D * d1c = (TH2D *) fs->Get("Momentum_Kp_Km_BoundStateKK");
    TH2D * d2c = (TH2D *) fs->Get("Momentum_Kp_Km_phi");
    TH2D * d3c = (TH2D *) fs->Get("Momentum_Kp_Km_Lambda1520");
    TH2D * d4c = (TH2D *) fs->Get("Momentum_Kp_Km_KK");
    TGraph * g0a = new TGraph(1000);
    TGraph * g1a = new TGraph(1000);
    TGraph * g2a = new TGraph(1000);
    TGraph * g3a = new TGraph(1000);
    TGraph * g4a = new TGraph(1000);
    TGraph * g0b = new TGraph(1000);
    TGraph * g1b = new TGraph(1000);
    TGraph * g2b = new TGraph(1000);
    TGraph * g3b = new TGraph(1000);
    TGraph * g4b = new TGraph(1000);
    TGraph * g0c = new TGraph(1000);
    TGraph * g1c = new TGraph(1000);
    TGraph * g2c = new TGraph(1000);
    TGraph * g3c = new TGraph(1000);
    TGraph * g4c = new TGraph(1000);
    double x, y;
    for (int i = 0; i < 1000; i++){
      d0a->GetRandom2(x, y);
      g0a->SetPoint(i, x, y);
      d1a->GetRandom2(x, y);
      g1a->SetPoint(i, x, y);
      d2a->GetRandom2(x, y);
      g2a->SetPoint(i, x, y);
      d3a->GetRandom2(x, y);
      g3a->SetPoint(i, x, y);
      d4a->GetRandom2(x, y);
      g4a->SetPoint(i, x, y);
      d0b->GetRandom2(x, y);
      g0b->SetPoint(i, x, y);
      d1b->GetRandom2(x, y);
      g1b->SetPoint(i, x, y);
      d2b->GetRandom2(x, y);
      g2b->SetPoint(i, x, y);
      d3b->GetRandom2(x, y);
      g3b->SetPoint(i, x, y);
      d4b->GetRandom2(x, y);
      g4b->SetPoint(i, x, y);
      d0c->GetRandom2(x, y);
      g0c->SetPoint(i, x, y);
      d1c->GetRandom2(x, y);
      g1c->SetPoint(i, x, y);
      d2c->GetRandom2(x, y);
      g2c->SetPoint(i, x, y);
      d3c->GetRandom2(x, y);
      g3c->SetPoint(i, x, y);
      d4c->GetRandom2(x, y);
      g4c->SetPoint(i, x, y);
    }
    //
    d0a->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0a->GetXaxis()->CenterTitle(true);
    d0a->GetXaxis()->SetTitleSize(0.06);
    d0a->GetXaxis()->SetTitleOffset(1.15);
    d0a->GetXaxis()->SetLabelSize(0.06);
    d0a->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetXaxis()->SetNdivisions(6, 5, 0);
    d0a->GetYaxis()->SetTitle("P(p) (GeV)");
    d0a->GetYaxis()->CenterTitle(true);
    d0a->GetYaxis()->SetTitleSize(0.06);
    d0a->GetYaxis()->SetTitleOffset(1.15);
    d0a->GetYaxis()->SetLabelSize(0.06);
    d0a->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0a->GetYaxis()->SetNdivisions(5, 5, 0);
    d0b->GetXaxis()->SetTitle("P(K^{-}) (GeV)");
    d0b->GetXaxis()->CenterTitle(true);
    d0b->GetXaxis()->SetTitleSize(0.06);
    d0b->GetXaxis()->SetTitleOffset(1.15);
    d0b->GetXaxis()->SetLabelSize(0.06);
    d0b->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetXaxis()->SetNdivisions(6, 5, 0);
    d0b->GetYaxis()->SetTitle("P(p) (GeV)");
    d0b->GetYaxis()->CenterTitle(true);
    d0b->GetYaxis()->SetTitleSize(0.06);
    d0b->GetYaxis()->SetTitleOffset(1.15);
    d0b->GetYaxis()->SetLabelSize(0.06);
    d0b->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0b->GetYaxis()->SetNdivisions(5, 5, 0);
    d0c->GetXaxis()->SetTitle("P(K^{+}) (GeV)");
    d0c->GetXaxis()->CenterTitle(true);
    d0c->GetXaxis()->SetTitleSize(0.06);
    d0c->GetXaxis()->SetTitleOffset(1.15);
    d0c->GetXaxis()->SetLabelSize(0.06);
    d0c->GetXaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetXaxis()->SetNdivisions(6, 5, 0);
    d0c->GetYaxis()->SetTitle("P(K^{-}) (GeV)");
    d0c->GetYaxis()->CenterTitle(true);
    d0c->GetYaxis()->SetTitleSize(0.06);
    d0c->GetYaxis()->SetTitleOffset(1.15);
    d0c->GetYaxis()->SetLabelSize(0.06);
    d0c->GetYaxis()->SetRangeUser(0.0, 2.0);
    d0c->GetYaxis()->SetNdivisions(5, 5, 0);
    //
    d0a->SetStats(0);
    d0b->SetStats(0);
    d0c->SetStats(0);
    //
    g0a->SetMarkerStyle(20);
    g0a->SetMarkerColor(1);
    g0a->SetMarkerSize(0.6);
    g1a->SetMarkerStyle(21);
    g1a->SetMarkerColor(4);
    g1a->SetMarkerSize(0.6);
    g2a->SetMarkerStyle(22);
    g2a->SetMarkerColor(2);
    g2a->SetMarkerSize(0.6);
    g3a->SetMarkerStyle(23);
    g3a->SetMarkerColor(6);
    g3a->SetMarkerSize(0.6);
    g4a->SetMarkerStyle(25);
    g4a->SetMarkerColor(7);
    g4a->SetMarkerSize(0.6);
    g0b->SetMarkerStyle(20);
    g0b->SetMarkerColor(1);
    g0b->SetMarkerSize(0.6);
    g1b->SetMarkerStyle(21);
    g1b->SetMarkerColor(4);
    g1b->SetMarkerSize(0.6);
    g2b->SetMarkerStyle(22);
    g2b->SetMarkerColor(2);
    g2b->SetMarkerSize(0.6);
    g3b->SetMarkerStyle(23);
    g3b->SetMarkerColor(6);
    g3b->SetMarkerSize(0.6);
    g4b->SetMarkerStyle(25);
    g4b->SetMarkerColor(7);
    g4b->SetMarkerSize(0.6);
    g0c->SetMarkerStyle(20);
    g0c->SetMarkerColor(1);
    g0c->SetMarkerSize(0.6);
    g1c->SetMarkerStyle(21);
    g1c->SetMarkerColor(4);
    g1c->SetMarkerSize(0.6);
    g2c->SetMarkerStyle(22);
    g2c->SetMarkerColor(2);
    g2c->SetMarkerSize(0.6);
    g3c->SetMarkerStyle(23);
    g3c->SetMarkerColor(6);
    g3c->SetMarkerSize(0.6);
    g4c->SetMarkerStyle(25);
    g4c->SetMarkerColor(7);
    g4c->SetMarkerSize(0.6);
    TLegend * leg = new TLegend(0.6, 0.7, 0.9, 0.9);
    leg->AddEntry(g0a, "pKK from N-#phi", "p");
    leg->AddEntry(g1a, "only KK from N-#phi", "p");
    leg->AddEntry(g2a, "#phi production", "p");
    leg->AddEntry(g3a, "#Lambda(1520) production", "p");
    leg->AddEntry(g4a, "direct KK production", "p");
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    //
    d0a->DrawClone("axis");
    g0a->DrawClone("psame");
    g1a->DrawClone("psame");
    g2a->DrawClone("psame");
    g3a->DrawClone("psame");
    g4a->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumcut.pdf(","pdf");//
    d0a->SetTitle("pKK from N-#phi");
    d0a->DrawClone("axis");
    d0a->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0a->SetTitle("only KK from N-#phi");
    d0a->DrawClone("axis");
    d1a->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0a->SetTitle("#phi production");
    d0a->DrawClone("axis");
    d2a->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0a->SetTitle("#Lambda(1520) production");
    d0a->DrawClone("axis");
    d3a->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//    
    d0a->SetTitle("direct KK production");
    d0a->DrawClone("axis");
    d4a->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    //
    d0b->DrawClone("axis");
    g0b->DrawClone("psame");
    g1b->DrawClone("psame");
    g2b->DrawClone("psame");
    g3b->DrawClone("psame");
    g4b->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumcut.pdf(","pdf");//
    d0b->SetTitle("pKK from N-#phi");
    d0b->DrawClone("axis");
    d0b->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0b->SetTitle("only KK from N-#phi");
    d0b->DrawClone("axis");
    d1b->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0b->SetTitle("#phi production");
    d0b->DrawClone("axis");
    d2b->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0b->SetTitle("#Lambda(1520) production");
    d0b->DrawClone("axis");
    d3b->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//    
    d0b->SetTitle("direct KK production");
    d0b->DrawClone("axis");
    d4b->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    //
    d0c->DrawClone("axis");
    g0c->DrawClone("psame");
    g1c->DrawClone("psame");
    g2c->DrawClone("psame");
    g3c->DrawClone("psame");
    g4c->DrawClone("psame");
    leg->DrawClone("same");
    c0->Print("gallary/Momentumcut.pdf(","pdf");//
    d0c->SetTitle("pKK from N-#phi");
    d0c->DrawClone("axis");
    d0c->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0c->SetTitle("only KK from N-#phi");
    d0c->DrawClone("axis");
    d1c->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0c->SetTitle("#phi production");
    d0c->DrawClone("axis");
    d2c->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//
    d0c->SetTitle("#Lambda(1520) production");
    d0c->DrawClone("axis");
    d3c->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf","pdf");//    
    d0c->SetTitle("direct KK production");
    d0c->DrawClone("axis");
    d4c->DrawClone("colsame");
    c0->Print("gallary/Momentumcut.pdf)","pdf");//
  }

  if (opt == 17){//P-theta cut
    //gStyle->SetPalette(52);
    TFile * fs = new TFile("result/cut.root", "r");
    TH2D * r0a = (TH2D *) fs->Get("PTheta_p_BoundStateAll");
    TH2D * r0b = (TH2D *) fs->Get("PTheta_Kp_BoundStateAll");
    TH2D * r0c = (TH2D *) fs->Get("PTheta_Km_BoundStateAll");
    TH2D * r1a = (TH2D *) fs->Get("PTheta_p_BoundStateKK");
    TH2D * r1b = (TH2D *) fs->Get("PTheta_Kp_BoundStateKK");
    TH2D * r1c = (TH2D *) fs->Get("PTheta_Km_BoundStateKK");
    TH2D * r2a = (TH2D *) fs->Get("PTheta_p_phi");
    TH2D * r2b = (TH2D *) fs->Get("PTheta_Kp_phi");
    TH2D * r2c = (TH2D *) fs->Get("PTheta_Km_phi");
    TH2D * r3a = (TH2D *) fs->Get("PTheta_p_Lambda1520");
    TH2D * r3b = (TH2D *) fs->Get("PTheta_Kp_Lambda1520");
    TH2D * r3c = (TH2D *) fs->Get("PTheta_Km_Lambda1520");
    TH2D * r4a = (TH2D *) fs->Get("PTheta_p_KK");
    TH2D * r4b = (TH2D *) fs->Get("PTheta_Kp_KK");
    TH2D * r4c = (TH2D *) fs->Get("PTheta_Km_KK");
    TH2D * rB = new TH2D("rB", "", 1, 0.0, 90.0, 1, 0.0, 2.0);
    rB->SetStats(0);
    rB->GetXaxis()->SetTitle("#theta (deg)");
    rB->GetXaxis()->CenterTitle(true);
    rB->GetXaxis()->SetTitleSize(0.06);
    rB->GetXaxis()->SetTitleOffset(1.15);
    rB->GetXaxis()->SetLabelSize(0.06);
    rB->GetXaxis()->SetRangeUser(0.0, 90.0);
    rB->GetXaxis()->SetNdivisions(6, 5, 0);
    rB->GetYaxis()->SetTitle("P (GeV)");
    rB->GetYaxis()->CenterTitle(true);
    rB->GetYaxis()->SetTitleSize(0.06);
    rB->GetYaxis()->SetTitleOffset(1.15);
    rB->GetYaxis()->SetLabelSize(0.06);
    rB->GetYaxis()->SetRangeUser(0.0, 2.0);
    rB->GetYaxis()->SetNdivisions(5, 5, 0);
    TCanvas * c0 = new TCanvas("c0", "", 800, 600);
    c0->SetLeftMargin(0.15);
    c0->SetBottomMargin(0.15);
    rB->SetTitle("proton from N-#phi");
    rB->DrawClone("axis");
    r0a->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf(", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r0b->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r0c->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");//
    rB->SetTitle("proton with N-#phi production");
    rB->DrawClone("axis");
    r1a->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{+} from N-#phi");
    rB->DrawClone("axis");
    r1b->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{-} from N-#phi");
    rB->DrawClone("axis");
    r1c->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");//
    rB->SetTitle("proton with #phi production");
    rB->DrawClone("axis");
    r2a->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{+} from #phi");
    rB->DrawClone("axis");
    r2b->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{-} from #phi");
    rB->DrawClone("axis");
    r2c->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");//
    rB->SetTitle("proton from #Lambda(1520)");
    rB->DrawClone("axis");
    r3a->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{+} with #Lambda(1520) production");
    rB->DrawClone("axis");
    r3b->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{-} from #Lambda(1520)");
    rB->DrawClone("axis");
    r3c->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");//
    rB->SetTitle("proton with direct KK production");
    rB->DrawClone("axis");
    r4a->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{+} from direct KK production");
    rB->DrawClone("axis");
    r4b->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf", "pdf");
    rB->SetTitle("K^{-} from direct KK production");
    rB->DrawClone("axis");
    r4c->Draw("colsame");
    c0->Print("gallary/PThetacut.pdf)", "pdf");//
  }



  return 0;
}
